<a href="https://colab.research.google.com/github/Anand3074/Anand3074/blob/main/1_7_24_3AM_RandomForest.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from google.colab import drive

In [3]:
drive.mount('/content/drive')

Mounted at /content/drive

In [4]:
df = pd.read_csv('/content/drive/My Drive/ML_Model/Race_Result_with_incidence.csv', low_memory=False)
df

,RaceID,Date,Venue,Horse,Age,Trainer,Jockey,Wt,Time,Dist,...,Odds,DistWin,Position,Racing_Incident,Allowance,Drawn,Sh,Won By,Rtg,Present_Rtg
0,1,02 Feb 2024,BANGALORE,EXCELLENT LASS,3,Rajesh Narredu,Neeraj Rawal,53.0,72.20,1200,...,3,NaN,1,1,NaN,1,A,Lnk,NaN,0
1,1,02 Feb 2024,BANGALORE,POSITANO,3,S S Attaollahi,F Norton,54.5,72.25,1200,...,7/4,NaN,2,0,NaN,9,A,3 3/4,NaN,0
2,1,02 Feb 2024,BANGALORE,TRUE PUNCH,3,M Rajendra Singh,Imran Chisty,54.5,72.86,1200,...,10,3.75,3,0,NaN,7,A,Snk,NaN,0
3,1,02 Feb 2024,BANGALORE,SILICON STAR,3,Warren Singh,A Ramu,53.0,72.89,1200,...,9,3.75,4,1,NaN,4,A,3 1/4,NaN,0
4,1,02 Feb 2024,BANGALORE,AMAZING RULER,3,B Prithviraj,Shreyas Singh S,54.5,73.41,1200,...,15,7.00,5,1,NaN,12,A,3/4,NaN,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
98227,9985,18 Nov 2018,MUMBAI,TIMELESS DEEDS,4,Narendra Lagad,J Chinoy,54.5,85.01,1400,...,6,1.25,2,1,NaN,1,A,Neck,52,27
98228,9985,18 Nov 2018,MUMBAI,COLLEGIUM,4,S K Sunderji,Dashrath Singh,54.5,85.05,1400,...,15,1.25,3,0,NaN,3,A,1 3/4,52,34
98229,9985,18 Nov 2018,MUMBAI,BOLD MARCH,5,Karthik Ganapathy,A Prakash,61.0,85.35,1400,...,40,3.00,4,1,-5,4,A,1 1/4,65,69
98230,9985,18 Nov 2018,MUMBAI,ELEGANT BEAUTY ...,5,Deepesh Narredu,Shrikant Kamble,56.0,85.53,1400,...,27,4.25,5,0,NaN,5,A,2,55,51
98231,9985,18 Nov 2018,MUMBAI,MOUNT MCKINLEY,5,Adhiraj S Jodha,P S Chouhan,53.5,85.87,1400,...,13,6.25,6,1,NaN,2,A,NaN,NaN,50

In [5]:
data = df.copy()

In [6]:
data['DistWin'] = data['DistWin'].fillna(0)

In [7]:
data['Inverse_Pos_Score'] = 1 / data['Position']

In [8]:
data['Win_Probability'] = data.groupby('RaceID')['Inverse_Pos_Score'].transform(lambda x: x / x.sum())

In [9]:
data

,RaceID,Date,Venue,Horse,Age,Trainer,Jockey,Wt,Time,Dist,...,Position,Racing_Incident,Allowance,Drawn,Sh,Won By,Rtg,Present_Rtg,Inverse_Pos_Score,Win_Probability
0,1,02 Feb 2024,BANGALORE,EXCELLENT LASS,3,Rajesh Narredu,Neeraj Rawal,53.0,72.20,1200,...,1,1,NaN,1,A,Lnk,NaN,0,1.000000,0.341417
1,1,02 Feb 2024,BANGALORE,POSITANO,3,S S Attaollahi,F Norton,54.5,72.25,1200,...,2,0,NaN,9,A,3 3/4,NaN,0,0.500000,0.170709
2,1,02 Feb 2024,BANGALORE,TRUE PUNCH,3,M Rajendra Singh,Imran Chisty,54.5,72.86,1200,...,3,0,NaN,7,A,Snk,NaN,0,0.333333,0.113806
3,1,02 Feb 2024,BANGALORE,SILICON STAR,3,Warren Singh,A Ramu,53.0,72.89,1200,...,4,1,NaN,4,A,3 1/4,NaN,0,0.250000,0.085354
4,1,02 Feb 2024,BANGALORE,AMAZING RULER,3,B Prithviraj,Shreyas Singh S,54.5,73.41,1200,...,5,1,NaN,12,A,3/4,NaN,0,0.200000,0.068283
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
98227,9985,18 Nov 2018,MUMBAI,TIMELESS DEEDS,4,Narendra Lagad,J Chinoy,54.5,85.01,1400,...,2,1,NaN,1,A,Neck,52,27,0.500000,0.204082
98228,9985,18 Nov 2018,MUMBAI,COLLEGIUM,4,S K Sunderji,Dashrath Singh,54.5,85.05,1400,...,3,0,NaN,3,A,1 3/4,52,34,0.333333,0.136054
98229,9985,18 Nov 2018,MUMBAI,BOLD MARCH,5,Karthik Ganapathy,A Prakash,61.0,85.35,1400,...,4,1,-5,4,A,1 1/4,65,69,0.250000,0.102041
98230,9985,18 Nov 2018,MUMBAI,ELEGANT BEAUTY ...,5,Deepesh Narredu,Shrikant Kamble,56.0,85.53,1400,...,5,0,NaN,5,A,2,55,51,0.200000,0.081633
98231,9985,18 Nov 2018,MUMBAI,MOUNT MCKINLEY,5,Adhiraj S Jodha,P S Chouhan,53.5,85.87,1400,...,6,1,NaN,2,A,NaN,NaN,50,0.166667,0.068027

In [11]:
data['Allowance'] = data['Allowance'].fillna(0)

In [12]:
data

,RaceID,Date,Venue,Horse,Age,Trainer,Jockey,Wt,Time,Dist,...,Position,Racing_Incident,Allowance,Drawn,Sh,Won By,Rtg,Present_Rtg,Inverse_Pos_Score,Win_Probability
0,1,02 Feb 2024,BANGALORE,EXCELLENT LASS,3,Rajesh Narredu,Neeraj Rawal,53.0,72.20,1200,...,1,1,0,1,A,Lnk,NaN,0,1.000000,0.341417
1,1,02 Feb 2024,BANGALORE,POSITANO,3,S S Attaollahi,F Norton,54.5,72.25,1200,...,2,0,0,9,A,3 3/4,NaN,0,0.500000,0.170709
2,1,02 Feb 2024,BANGALORE,TRUE PUNCH,3,M Rajendra Singh,Imran Chisty,54.5,72.86,1200,...,3,0,0,7,A,Snk,NaN,0,0.333333,0.113806
3,1,02 Feb 2024,BANGALORE,SILICON STAR,3,Warren Singh,A Ramu,53.0,72.89,1200,...,4,1,0,4,A,3 1/4,NaN,0,0.250000,0.085354
4,1,02 Feb 2024,BANGALORE,AMAZING RULER,3,B Prithviraj,Shreyas Singh S,54.5,73.41,1200,...,5,1,0,12,A,3/4,NaN,0,0.200000,0.068283
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
98227,9985,18 Nov 2018,MUMBAI,TIMELESS DEEDS,4,Narendra Lagad,J Chinoy,54.5,85.01,1400,...,2,1,0,1,A,Neck,52,27,0.500000,0.204082
98228,9985,18 Nov 2018,MUMBAI,COLLEGIUM,4,S K Sunderji,Dashrath Singh,54.5,85.05,1400,...,3,0,0,3,A,1 3/4,52,34,0.333333,0.136054
98229,9985,18 Nov 2018,MUMBAI,BOLD MARCH,5,Karthik Ganapathy,A Prakash,61.0,85.35,1400,...,4,1,-5,4,A,1 1/4,65,69,0.250000,0.102041
98230,9985,18 Nov 2018,MUMBAI,ELEGANT BEAUTY ...,5,Deepesh Narredu,Shrikant Kamble,56.0,85.53,1400,...,5,0,0,5,A,2,55,51,0.200000,0.081633
98231,9985,18 Nov 2018,MUMBAI,MOUNT MCKINLEY,5,Adhiraj S Jodha,P S Chouhan,53.5,85.87,1400,...,6,1,0,2,A,NaN,NaN,50,0.166667,0.068027

In [13]:
data['Normalized_DistWin'] = data.groupby('RaceID')['DistWin'].transform(lambda x: (x - x.min()) / (x.max() - x.min()))
data

,RaceID,Date,Venue,Horse,Age,Trainer,Jockey,Wt,Time,Dist,...,Racing_Incident,Allowance,Drawn,Sh,Won By,Rtg,Present_Rtg,Inverse_Pos_Score,Win_Probability,Normalized_DistWin
0,1,02 Feb 2024,BANGALORE,EXCELLENT LASS,3,Rajesh Narredu,Neeraj Rawal,53.0,72.20,1200,...,1,0,1,A,Lnk,NaN,0,1.000000,0.341417,0.000000
1,1,02 Feb 2024,BANGALORE,POSITANO,3,S S Attaollahi,F Norton,54.5,72.25,1200,...,0,0,9,A,3 3/4,NaN,0,0.500000,0.170709,0.000000
2,1,02 Feb 2024,BANGALORE,TRUE PUNCH,3,M Rajendra Singh,Imran Chisty,54.5,72.86,1200,...,0,0,7,A,Snk,NaN,0,0.333333,0.113806,0.294118
3,1,02 Feb 2024,BANGALORE,SILICON STAR,3,Warren Singh,A Ramu,53.0,72.89,1200,...,1,0,4,A,3 1/4,NaN,0,0.250000,0.085354,0.294118
4,1,02 Feb 2024,BANGALORE,AMAZING RULER,3,B Prithviraj,Shreyas Singh S,54.5,73.41,1200,...,1,0,12,A,3/4,NaN,0,0.200000,0.068283,0.549020
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
98227,9985,18 Nov 2018,MUMBAI,TIMELESS DEEDS,4,Narendra Lagad,J Chinoy,54.5,85.01,1400,...,1,0,1,A,Neck,52,27,0.500000,0.204082,0.200000
98228,9985,18 Nov 2018,MUMBAI,COLLEGIUM,4,S K Sunderji,Dashrath Singh,54.5,85.05,1400,...,0,0,3,A,1 3/4,52,34,0.333333,0.136054,0.200000
98229,9985,18 Nov 2018,MUMBAI,BOLD MARCH,5,Karthik Ganapathy,A Prakash,61.0,85.35,1400,...,1,-5,4,A,1 1/4,65,69,0.250000,0.102041,0.480000
98230,9985,18 Nov 2018,MUMBAI,ELEGANT BEAUTY ...,5,Deepesh Narredu,Shrikant Kamble,56.0,85.53,1400,...,0,0,5,A,2,55,51,0.200000,0.081633,0.680000
98231,9985,18 Nov 2018,MUMBAI,MOUNT MCKINLEY,5,Adhiraj S Jodha,P S Chouhan,53.5,85.87,1400,...,1,0,2,A,NaN,NaN,50,0.166667,0.068027,1.000000

In [14]:
data.isnull().sum()

RaceID                    0
Date                      0
Venue                     0
Horse                     0
Age                       0
Trainer                  29
Jockey                    0
Wt                        0
Time                      0
Dist                      0
Class                   538
Odds                  29138
DistWin                   0
Position                  0
Racing_Incident           0
Allowance                 0
Drawn                    13
Sh                       31
Won By                10856
Rtg                   15705
Present_Rtg               0
Inverse_Pos_Score         0
Win_Probability           0
Normalized_DistWin       31
dtype: int64

In [15]:

def adjust_win_probability(row):
    base_probability = row['Win_Probability']
    dist_win_factor = 1 - row['Normalized_DistWin']
    adjusted_probability = base_probability * dist_win_factor
    return adjusted_probability

In [16]:
data['Probability'] = data.apply(adjust_win_probability, axis=1)

In [17]:
data['Probability'] = data.groupby('RaceID')['Probability'].transform(lambda x: x / x.sum())

In [18]:
data['Date'] = pd.to_datetime(data['Date'])

In [19]:
data = data.drop('Trainer', axis=1)

In [20]:
data

,RaceID,Date,Venue,Horse,Age,Jockey,Wt,Time,Dist,Class,...,Allowance,Drawn,Sh,Won By,Rtg,Present_Rtg,Inverse_Pos_Score,Win_Probability,Normalized_DistWin,Probability
0,1,2024-02-02,BANGALORE,EXCELLENT LASS,3,Neeraj Rawal,53.0,72.20,1200,1.0,...,0,1,A,Lnk,NaN,0,1.000000,0.341417,0.000000,0.457575
1,1,2024-02-02,BANGALORE,POSITANO,3,F Norton,54.5,72.25,1200,1.0,...,0,9,A,3 3/4,NaN,0,0.500000,0.170709,0.000000,0.228787
2,1,2024-02-02,BANGALORE,TRUE PUNCH,3,Imran Chisty,54.5,72.86,1200,1.0,...,0,7,A,Snk,NaN,0,0.333333,0.113806,0.294118,0.107665
3,1,2024-02-02,BANGALORE,SILICON STAR,3,A Ramu,53.0,72.89,1200,1.0,...,0,4,A,3 1/4,NaN,0,0.250000,0.085354,0.294118,0.080749
4,1,2024-02-02,BANGALORE,AMAZING RULER,3,Shreyas Singh S,54.5,73.41,1200,1.0,...,0,12,A,3/4,NaN,0,0.200000,0.068283,0.549020,0.041271
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
98227,9985,2018-11-18,MUMBAI,TIMELESS DEEDS,4,J Chinoy,54.5,85.01,1400,3.0,...,0,1,A,Neck,52,27,0.500000,0.204082,0.200000,0.214977
98228,9985,2018-11-18,MUMBAI,COLLEGIUM,4,Dashrath Singh,54.5,85.05,1400,3.0,...,0,3,A,1 3/4,52,34,0.333333,0.136054,0.200000,0.143318
98229,9985,2018-11-18,MUMBAI,BOLD MARCH,5,A Prakash,61.0,85.35,1400,3.0,...,-5,4,A,1 1/4,65,69,0.250000,0.102041,0.480000,0.069867
98230,9985,2018-11-18,MUMBAI,ELEGANT BEAUTY ...,5,Shrikant Kamble,56.0,85.53,1400,3.0,...,0,5,A,2,55,51,0.200000,0.081633,0.680000,0.034396
98231,9985,2018-11-18,MUMBAI,MOUNT MCKINLEY,5,P S Chouhan,53.5,85.87,1400,3.0,...,0,2,A,NaN,NaN,50,0.166667,0.068027,1.000000,0.000000

In [21]:

horse_performance_metrics = data.groupby('Horse').apply(
    lambda x: pd.Series({
        'Total_Top_3': (x['Position'] <= 3).sum(),
        'Win_PCT': round((x['Position'] == 1).mean() * 100, 2)
    })
).reset_index()

In [22]:
data = data.merge(horse_performance_metrics, on='Horse', how='left')

In [23]:
data

,RaceID,Date,Venue,Horse,Age,Jockey,Wt,Time,Dist,Class,...,Sh,Won By,Rtg,Present_Rtg,Inverse_Pos_Score,Win_Probability,Normalized_DistWin,Probability,Total_Top_3,Win_PCT
0,1,2024-02-02,BANGALORE,EXCELLENT LASS,3,Neeraj Rawal,53.0,72.20,1200,1.0,...,A,Lnk,NaN,0,1.000000,0.341417,0.000000,0.457575,2.0,100.00
1,1,2024-02-02,BANGALORE,POSITANO,3,F Norton,54.5,72.25,1200,1.0,...,A,3 3/4,NaN,0,0.500000,0.170709,0.000000,0.228787,1.0,0.00
2,1,2024-02-02,BANGALORE,TRUE PUNCH,3,Imran Chisty,54.5,72.86,1200,1.0,...,A,Snk,NaN,0,0.333333,0.113806,0.294118,0.107665,2.0,0.00
3,1,2024-02-02,BANGALORE,SILICON STAR,3,A Ramu,53.0,72.89,1200,1.0,...,A,3 1/4,NaN,0,0.250000,0.085354,0.294118,0.080749,2.0,0.00
4,1,2024-02-02,BANGALORE,AMAZING RULER,3,Shreyas Singh S,54.5,73.41,1200,1.0,...,A,3/4,NaN,0,0.200000,0.068283,0.549020,0.041271,1.0,50.00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
98227,9985,2018-11-18,MUMBAI,TIMELESS DEEDS,4,J Chinoy,54.5,85.01,1400,3.0,...,A,Neck,52,27,0.500000,0.204082,0.200000,0.214977,5.0,3.85
98228,9985,2018-11-18,MUMBAI,COLLEGIUM,4,Dashrath Singh,54.5,85.05,1400,3.0,...,A,1 3/4,52,34,0.333333,0.136054,0.200000,0.143318,4.0,9.09
98229,9985,2018-11-18,MUMBAI,BOLD MARCH,5,A Prakash,61.0,85.35,1400,3.0,...,A,1 1/4,65,69,0.250000,0.102041,0.480000,0.069867,2.0,22.22
98230,9985,2018-11-18,MUMBAI,ELEGANT BEAUTY ...,5,Shrikant Kamble,56.0,85.53,1400,3.0,...,A,2,55,51,0.200000,0.081633,0.680000,0.034396,1.0,9.09
98231,9985,2018-11-18,MUMBAI,MOUNT MCKINLEY,5,P S Chouhan,53.5,85.87,1400,3.0,...,A,NaN,NaN,50,0.166667,0.068027,1.000000,0.000000,0.0,0.00

In [24]:
data.loc[:, 'Wt'] = pd.to_numeric(data['Wt'], errors='coerce')

In [25]:
data['Wt'] = data['Wt'].fillna(data['Wt'].mean())

In [27]:
data['Avg_Wt'] = data.groupby('Horse')['Wt'].transform('mean')

In [28]:
data

,RaceID,Date,Venue,Horse,Age,Jockey,Wt,Time,Dist,Class,...,Won By,Rtg,Present_Rtg,Inverse_Pos_Score,Win_Probability,Normalized_DistWin,Probability,Total_Top_3,Win_PCT,Avg_Wt
0,1,2024-02-02,BANGALORE,EXCELLENT LASS,3,Neeraj Rawal,53.0,72.20,1200,1.0,...,Lnk,NaN,0,1.000000,0.341417,0.000000,0.457575,2.0,100.00,53.750000
1,1,2024-02-02,BANGALORE,POSITANO,3,F Norton,54.5,72.25,1200,1.0,...,3 3/4,NaN,0,0.500000,0.170709,0.000000,0.228787,1.0,0.00,54.500000
2,1,2024-02-02,BANGALORE,TRUE PUNCH,3,Imran Chisty,54.5,72.86,1200,1.0,...,Snk,NaN,0,0.333333,0.113806,0.294118,0.107665,2.0,0.00,55.250000
3,1,2024-02-02,BANGALORE,SILICON STAR,3,A Ramu,53.0,72.89,1200,1.0,...,3 1/4,NaN,0,0.250000,0.085354,0.294118,0.080749,2.0,0.00,54.000000
4,1,2024-02-02,BANGALORE,AMAZING RULER,3,Shreyas Singh S,54.5,73.41,1200,1.0,...,3/4,NaN,0,0.200000,0.068283,0.549020,0.041271,1.0,50.00,55.250000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
98227,9985,2018-11-18,MUMBAI,TIMELESS DEEDS,4,J Chinoy,54.5,85.01,1400,3.0,...,Neck,52,27,0.500000,0.204082,0.200000,0.214977,5.0,3.85,56.038462
98228,9985,2018-11-18,MUMBAI,COLLEGIUM,4,Dashrath Singh,54.5,85.05,1400,3.0,...,1 3/4,52,34,0.333333,0.136054,0.200000,0.143318,4.0,9.09,55.500000
98229,9985,2018-11-18,MUMBAI,BOLD MARCH,5,A Prakash,61.0,85.35,1400,3.0,...,1 1/4,65,69,0.250000,0.102041,0.480000,0.069867,2.0,22.22,55.444444
98230,9985,2018-11-18,MUMBAI,ELEGANT BEAUTY ...,5,Shrikant Kamble,56.0,85.53,1400,3.0,...,2,55,51,0.200000,0.081633,0.680000,0.034396,1.0,9.09,56.590909
98231,9985,2018-11-18,MUMBAI,MOUNT MCKINLEY,5,P S Chouhan,53.5,85.87,1400,3.0,...,NaN,NaN,50,0.166667,0.068027,1.000000,0.000000,0.0,0.00,55.000000

In [29]:
data.isnull().sum()

RaceID                    0
Date                      0
Venue                     0
Horse                     0
Age                       0
Jockey                    0
Wt                        0
Time                      0
Dist                      0
Class                   538
Odds                  29138
DistWin                   0
Position                  0
Racing_Incident           0
Allowance                 0
Drawn                    13
Sh                       31
Won By                10856
Rtg                   15705
Present_Rtg               0
Inverse_Pos_Score         0
Win_Probability           0
Normalized_DistWin       31
Probability              31
Total_Top_3               0
Win_PCT                   0
Avg_Wt                    0
dtype: int64

In [53]:
Jockey = pd.read_csv('/content/drive/My Drive/ML_Model/Jockey_Ranking.csv', low_memory=False)
Jockey = Jockey.rename(columns={'Trainer': 'Jockey'})
Jockey = Jockey.rename(columns={'JO5KEY_RANK': 'Jockey_Rank'})
Jockey = Jockey.rename(columns={'Win%': 'Jockey_Win_Pct'})
Jockey = Jockey.rename(columns={'Top 4': 'Jockey_Top_4'})
Jockey = Jockey.rename(columns={'Total Runs': 'Jockey_Total_Runs'})
Jockey = Jockey.drop(['RANKING'], axis=1)
Jockey['Jockey'] = Jockey['Jockey'].str.title()
Jockey

,Jockey,Jockey_Top_4,Jockey_Total_Runs,Jockey_Win_Pct,Jockey_Rank
0,Vivek G,213,316,21.42,2
1,P Sai Kumar,122,236,10.66,4
2,P Trevor,186,221,28.63,1
3,Hindu Singh,137,219,19.73,5
4,Koshi Kumar,90,213,12.68,5
...,...,...,...,...,...
233,S P Ranjane,0,1,0.00,5
234,Mudassar Nazar,0,1,0.00,5
235,Naveen Kumar,0,1,0.00,5
236,Nds,0,0,0.00,5
237,Withdrawn,0,0,0.00,5

In [66]:
data= data.drop(['Jockey_Rank_x',	'Win%',	'Jockey_Rank_y',	'Jockey_Top_4',	'Jockey_Total_Runs',	'Jockey_Win_Pct',	'Jockey_Rank',], axis=1)

In [67]:
data = data.merge(Jockey, on='Jockey', how='left')
data.isnull().sum()

RaceID                    0
Date                      0
Venue                     0
Horse                     0
Age                       0
Jockey                    0
Wt                        0
Time                      0
Dist                      0
Class                   538
Odds                  29138
DistWin                   0
Position                  0
Racing_Incident           0
Allowance                 0
Drawn                    13
Sh                       31
Won By                10856
Rtg                   15705
Present_Rtg               0
Inverse_Pos_Score         0
Win_Probability           0
Normalized_DistWin       31
Probability              31
Total_Top_3               0
Win_PCT                   0
Avg_Wt                    0
Jockey_Top_4          25272
Jockey_Total_Runs     25272
Jockey_Win_Pct        25272
Jockey_Rank           25272
dtype: int64

In [68]:
data

,RaceID,Date,Venue,Horse,Age,Jockey,Wt,Time,Dist,Class,...,Win_Probability,Normalized_DistWin,Probability,Total_Top_3,Win_PCT,Avg_Wt,Jockey_Top_4,Jockey_Total_Runs,Jockey_Win_Pct,Jockey_Rank
0,1,2024-02-02,BANGALORE,EXCELLENT LASS,3,Neeraj Rawal,53.0,72.20,1200,1.0,...,0.341417,0.000000,0.457575,2.0,100.00,53.750000,138.0,206.0,11.31,4.0
1,1,2024-02-02,BANGALORE,POSITANO,3,F Norton,54.5,72.25,1200,1.0,...,0.170709,0.000000,0.228787,1.0,0.00,54.500000,23.0,38.0,13.26,5.0
2,1,2024-02-02,BANGALORE,TRUE PUNCH,3,Imran Chisty,54.5,72.86,1200,1.0,...,0.113806,0.294118,0.107665,2.0,0.00,55.250000,101.0,158.0,15.62,4.0
3,1,2024-02-02,BANGALORE,SILICON STAR,3,A Ramu,53.0,72.89,1200,1.0,...,0.085354,0.294118,0.080749,2.0,0.00,54.000000,11.0,33.0,3.70,5.0
4,1,2024-02-02,BANGALORE,AMAZING RULER,3,Shreyas Singh S,54.5,73.41,1200,1.0,...,0.068283,0.549020,0.041271,1.0,50.00,55.250000,13.0,44.0,6.81,5.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
98227,9985,2018-11-18,MUMBAI,TIMELESS DEEDS,4,J Chinoy,54.5,85.01,1400,3.0,...,0.204082,0.200000,0.214977,5.0,3.85,56.038462,9.0,26.0,7.69,5.0
98228,9985,2018-11-18,MUMBAI,COLLEGIUM,4,Dashrath Singh,54.5,85.05,1400,3.0,...,0.136054,0.200000,0.143318,4.0,9.09,55.500000,1.0,6.0,0.00,5.0
98229,9985,2018-11-18,MUMBAI,BOLD MARCH,5,A Prakash,61.0,85.35,1400,3.0,...,0.102041,0.480000,0.069867,2.0,22.22,55.444444,NaN,NaN,NaN,NaN
98230,9985,2018-11-18,MUMBAI,ELEGANT BEAUTY ...,5,Shrikant Kamble,56.0,85.53,1400,3.0,...,0.081633,0.680000,0.034396,1.0,9.09,56.590909,18.0,41.0,6.52,5.0
98231,9985,2018-11-18,MUMBAI,MOUNT MCKINLEY,5,P S Chouhan,53.5,85.87,1400,3.0,...,0.068027,1.000000,0.000000,0.0,0.00,55.000000,96.0,134.0,19.70,2.0

In [72]:
data['Won'] = (data['Position'] == 1).astype(int)

In [74]:
nan_jockey_data = data[data['Jockey_Rank'].isna()]
nan_jockey_data

,RaceID,Date,Venue,Horse,Age,Jockey,Wt,Time,Dist,Class,...,Normalized_DistWin,Probability,Total_Top_3,Win_PCT,Avg_Wt,Jockey_Top_4,Jockey_Total_Runs,Jockey_Win_Pct,Jockey_Rank,Won
8,1,2024-02-02,BANGALORE,BOURBONAIRE,3,A Ashok Kumar,54.5,74.19,1200,1.0,...,0.882353,0.005981,0.0,0.00,54.500000,NaN,NaN,NaN,NaN,0
35,4,2024-02-10,BANGALORE,QUEEN OF KINGS,3,A Ashok Kumar,54.5,89.89,1400,6.0,...,0.859060,0.005465,0.0,0.00,54.500000,NaN,NaN,NaN,NaN,0
51,6,2024-03-16,BANGALORE,EL ALAMEIN,5,R Rayan Ahmed,54.5,87.52,1400,4.0,...,0.194175,0.045970,1.0,0.00,57.071429,NaN,NaN,NaN,NaN,0
83,9,2023-11-03,BANGALORE,MAYBACH,4,R Girish,50.5,78.07,1200,4.0,...,0.415686,0.018675,1.0,0.00,57.071429,NaN,NaN,NaN,NaN,0
126,14,2023-02-10,BANGALORE,EMPRESS BELLA,4,P Mani,58.5,78.20,1200,4.0,...,1.000000,0.000000,0.0,0.00,58.700000,NaN,NaN,NaN,NaN,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
98212,9982,2019-02-21,MUMBAI,JOHN CABOT ...,5,Nirmal Jodha,60.5,0.00,1600,3.0,...,0.582090,0.041579,2.0,0.00,58.111111,NaN,NaN,NaN,NaN,0
98217,9983,2019-01-24,MUMBAI,ARABIA,4,Leigh Roche,57.5,98.30,1600,2.0,...,0.272727,0.127592,2.0,25.00,56.000000,NaN,NaN,NaN,NaN,0
98221,9984,2018-12-08,KOLKATA,ADJUDICATE,3,David Allan,55.5,95.40,1600,1.0,...,0.000000,0.757202,10.0,50.00,56.550000,NaN,NaN,NaN,NaN,1
98226,9985,2018-11-18,MUMBAI,SPITFIRE,3,Leigh Roche,55.0,84.81,1400,3.0,...,0.000000,0.537442,3.0,16.67,57.000000,NaN,NaN,NaN,NaN,1
98229,9985,2018-11-18,MUMBAI,BOLD MARCH,5,A Prakash,61.0,85.35,1400,3.0,...,0.480000,0.069867,2.0,22.22,55.444444,NaN,NaN,NaN,NaN,0

In [75]:
jockey_stats = nan_jockey_data.groupby('Jockey').agg({
    'Won': 'mean',
    'Horse': 'count',
    'Position': lambda x: (x <= 3).sum()  # Count top 3 finishes
}).reset_index()
jockey_stats.rename(columns={'Horse': 'Total_Runs', 'Position': 'Total_Top_3'}, inplace=True)

In [76]:
jockey_stats['Composite_Rank'] = (
    jockey_stats['Won'] * 0.5  # Weight for Win Percentage
    + jockey_stats['Total_Runs'] * 0.15  # Weight for Total Runs
    + jockey_stats['Total_Top_3'] * 0.35  # Weight for Total Top 3
)

In [140]:
jockey_stats['Jockey_Rank'] = pd.qcut(jockey_stats['Composite_Rank'], q=3, labels=['5', '4', '3',])

In [141]:
data = pd.merge(data, jockey_stats[['Jockey', 'Jockey_Rank']], on='Jockey', how='left', suffixes=('', '_new'))

In [142]:
data

,RaceID,Date,Venue,Horse,Age,Jockey,Wt,Time,Dist,Class,...,Jockey_Win_Pct,Jockey_Rank,Won,Avg_Probability,Speed_Rating,Recent_5_Wins,Recent_5_Top_3,Recent_5_Incidents,Incident_Last_Race,Jockey_Rank_new
0,1,2024-02-02,BANGALORE,AMAZING RULER,3,Shreyas Singh S,54.5,73.41,1200,1.0,...,6.81,5.0,0,0.262586,628.000000,0.0,0.0,1.0,NaN,NaN
1,1,2024-02-02,BANGALORE,BOURBONAIRE,3,A Ashok Kumar,54.5,74.19,1200,1.0,...,NaN,2.0,0,0.005981,627.000000,0.0,0.0,0.0,NaN,3
2,1,2024-02-02,BANGALORE,BOWEN,3,Arshad Alam,53.0,73.53,1200,1.0,...,3.45,5.0,0,0.034705,626.000000,0.0,0.0,1.0,NaN,NaN
3,1,2024-02-02,BANGALORE,EXCELLENT LASS,3,Neeraj Rawal,53.0,72.20,1200,1.0,...,11.31,4.0,1,0.418630,661.000000,1.0,1.0,0.0,NaN,NaN
4,1,2024-02-02,BANGALORE,GOLDEN STRIDE,3,Surya P,53.0,74.43,1200,1.0,...,3.33,5.0,0,0.000000,602.000000,0.0,0.0,1.0,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
98227,9985,2018-11-18,MUMBAI,COLLEGIUM,4,Dashrath Singh,54.5,85.05,1400,3.0,...,0.00,5.0,0,0.088698,640.000000,0.0,2.0,1.0,0.0,NaN
98228,9985,2018-11-18,MUMBAI,ELEGANT BEAUTY ...,5,Shrikant Kamble,56.0,85.53,1400,3.0,...,6.52,5.0,0,0.106164,629.363636,0.0,0.0,0.0,0.0,NaN
98229,9985,2018-11-18,MUMBAI,MOUNT MCKINLEY,5,P S Chouhan,53.5,85.87,1400,3.0,...,19.70,2.0,0,0.000000,646.000000,0.0,0.0,1.0,0.0,NaN
98230,9985,2018-11-18,MUMBAI,SPITFIRE,3,Leigh Roche,55.0,84.81,1400,3.0,...,NaN,2.0,1,0.119113,669.000000,1.0,1.0,0.0,0.0,3
98231,9985,2018-11-18,MUMBAI,TIMELESS DEEDS,4,J Chinoy,54.5,85.01,1400,3.0,...,7.69,5.0,0,0.058736,643.153846,0.0,2.0,2.0,0.0,NaN

In [143]:
data['Jockey_Rank'] = data['Jockey_Rank'].combine_first(data['Jockey_Rank_new'])

In [144]:
data.drop(columns=['Jockey_Rank_new'], inplace=True)

In [145]:
data

,RaceID,Date,Venue,Horse,Age,Jockey,Wt,Time,Dist,Class,...,Jockey_Total_Runs,Jockey_Win_Pct,Jockey_Rank,Won,Avg_Probability,Speed_Rating,Recent_5_Wins,Recent_5_Top_3,Recent_5_Incidents,Incident_Last_Race
0,1,2024-02-02,BANGALORE,AMAZING RULER,3,Shreyas Singh S,54.5,73.41,1200,1.0,...,44.0,6.81,5.0,0,0.262586,628.000000,0.0,0.0,1.0,NaN
1,1,2024-02-02,BANGALORE,BOURBONAIRE,3,A Ashok Kumar,54.5,74.19,1200,1.0,...,NaN,NaN,2.0,0,0.005981,627.000000,0.0,0.0,0.0,NaN
2,1,2024-02-02,BANGALORE,BOWEN,3,Arshad Alam,53.0,73.53,1200,1.0,...,42.0,3.45,5.0,0,0.034705,626.000000,0.0,0.0,1.0,NaN
3,1,2024-02-02,BANGALORE,EXCELLENT LASS,3,Neeraj Rawal,53.0,72.20,1200,1.0,...,206.0,11.31,4.0,1,0.418630,661.000000,1.0,1.0,0.0,NaN
4,1,2024-02-02,BANGALORE,GOLDEN STRIDE,3,Surya P,53.0,74.43,1200,1.0,...,30.0,3.33,5.0,0,0.000000,602.000000,0.0,0.0,1.0,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
98227,9985,2018-11-18,MUMBAI,COLLEGIUM,4,Dashrath Singh,54.5,85.05,1400,3.0,...,6.0,0.00,5.0,0,0.088698,640.000000,0.0,2.0,1.0,0.0
98228,9985,2018-11-18,MUMBAI,ELEGANT BEAUTY ...,5,Shrikant Kamble,56.0,85.53,1400,3.0,...,41.0,6.52,5.0,0,0.106164,629.363636,0.0,0.0,0.0,0.0
98229,9985,2018-11-18,MUMBAI,MOUNT MCKINLEY,5,P S Chouhan,53.5,85.87,1400,3.0,...,134.0,19.70,2.0,0,0.000000,646.000000,0.0,0.0,1.0,0.0
98230,9985,2018-11-18,MUMBAI,SPITFIRE,3,Leigh Roche,55.0,84.81,1400,3.0,...,NaN,NaN,2.0,1,0.119113,669.000000,1.0,1.0,0.0,0.0
98231,9985,2018-11-18,MUMBAI,TIMELESS DEEDS,4,J Chinoy,54.5,85.01,1400,3.0,...,26.0,7.69,5.0,0,0.058736,643.153846,0.0,2.0,2.0,0.0

In [83]:
data.isnull().sum()

RaceID                    0
Date                      0
Venue                     0
Horse                     0
Age                       0
Jockey                    0
Wt                        0
Time                      0
Dist                      0
Class                   538
Odds                  29138
DistWin                   0
Position                  0
Racing_Incident           0
Allowance                 0
Drawn                    13
Sh                       31
Won By                10856
Rtg                   15705
Present_Rtg               0
Inverse_Pos_Score         0
Win_Probability           0
Normalized_DistWin       31
Probability              31
Total_Top_3               0
Win_PCT                   0
Avg_Wt                    0
Jockey_Top_4          25272
Jockey_Total_Runs     25272
Jockey_Win_Pct        25272
Jockey_Rank               0
Won                       0
dtype: int64

In [84]:
Avg_Probability = data.groupby('Horse')['Probability'].mean().reset_index()

In [85]:
Avg_Probability.columns = ['Horse', 'Avg_Probability']

In [86]:
data = data.merge(Avg_Probability, on='Horse', how='left')

In [87]:
data

,RaceID,Date,Venue,Horse,Age,Jockey,Wt,Time,Dist,Class,...,Probability,Total_Top_3,Win_PCT,Avg_Wt,Jockey_Top_4,Jockey_Total_Runs,Jockey_Win_Pct,Jockey_Rank,Won,Avg_Probability
0,1,2024-02-02,BANGALORE,EXCELLENT LASS,3,Neeraj Rawal,53.0,72.20,1200,1.0,...,0.457575,2.0,100.00,53.750000,138.0,206.0,11.31,4.0,1,0.418630
1,1,2024-02-02,BANGALORE,POSITANO,3,F Norton,54.5,72.25,1200,1.0,...,0.228787,1.0,0.00,54.500000,23.0,38.0,13.26,5.0,0,0.228787
2,1,2024-02-02,BANGALORE,TRUE PUNCH,3,Imran Chisty,54.5,72.86,1200,1.0,...,0.107665,2.0,0.00,55.250000,101.0,158.0,15.62,4.0,0,0.111439
3,1,2024-02-02,BANGALORE,SILICON STAR,3,A Ramu,53.0,72.89,1200,1.0,...,0.080749,2.0,0.00,54.000000,11.0,33.0,3.70,5.0,0,0.112609
4,1,2024-02-02,BANGALORE,AMAZING RULER,3,Shreyas Singh S,54.5,73.41,1200,1.0,...,0.041271,1.0,50.00,55.250000,13.0,44.0,6.81,5.0,0,0.262586
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
98227,9985,2018-11-18,MUMBAI,TIMELESS DEEDS,4,J Chinoy,54.5,85.01,1400,3.0,...,0.214977,5.0,3.85,56.038462,9.0,26.0,7.69,5.0,0,0.058736
98228,9985,2018-11-18,MUMBAI,COLLEGIUM,4,Dashrath Singh,54.5,85.05,1400,3.0,...,0.143318,4.0,9.09,55.500000,1.0,6.0,0.00,5.0,0,0.088698
98229,9985,2018-11-18,MUMBAI,BOLD MARCH,5,A Prakash,61.0,85.35,1400,3.0,...,0.069867,2.0,22.22,55.444444,NaN,NaN,NaN,2,0,0.117454
98230,9985,2018-11-18,MUMBAI,ELEGANT BEAUTY ...,5,Shrikant Kamble,56.0,85.53,1400,3.0,...,0.034396,1.0,9.09,56.590909,18.0,41.0,6.52,5.0,0,0.106164
98231,9985,2018-11-18,MUMBAI,MOUNT MCKINLEY,5,P S Chouhan,53.5,85.87,1400,3.0,...,0.000000,0.0,0.00,55.000000,96.0,134.0,19.70,2.0,0,0.000000

In [92]:
data.loc[data['Position'] == 1, 'Racing_Incident'] = 0

In [93]:
data[['Position', 'Racing_Incident']]

       Position  Racing_Incident
0             1                0
1             2                0
2             3                0
3             4                1
4             5                1
...         ...              ...
98227         2                1
98228         3                0
98229         4                1
98230         5                0
98231         6                1

[98232 rows x 2 columns]

In [96]:
data['Jockey_Rank'] = data['Jockey_Rank'].astype(float)

In [100]:
data

,RaceID,Date,Venue,Horse,Age,Jockey,Wt,Time,Dist,Class,...,Probability,Total_Top_3,Win_PCT,Avg_Wt,Jockey_Top_4,Jockey_Total_Runs,Jockey_Win_Pct,Jockey_Rank,Won,Avg_Probability
0,1,2024-02-02,BANGALORE,EXCELLENT LASS,3,Neeraj Rawal,53.0,72.20,1200,1.0,...,0.457575,2.0,100.00,53.750000,138.0,206.0,11.31,4.0,1,0.418630
1,1,2024-02-02,BANGALORE,POSITANO,3,F Norton,54.5,72.25,1200,1.0,...,0.228787,1.0,0.00,54.500000,23.0,38.0,13.26,5.0,0,0.228787
2,1,2024-02-02,BANGALORE,TRUE PUNCH,3,Imran Chisty,54.5,72.86,1200,1.0,...,0.107665,2.0,0.00,55.250000,101.0,158.0,15.62,4.0,0,0.111439
3,1,2024-02-02,BANGALORE,SILICON STAR,3,A Ramu,53.0,72.89,1200,1.0,...,0.080749,2.0,0.00,54.000000,11.0,33.0,3.70,5.0,0,0.112609
4,1,2024-02-02,BANGALORE,AMAZING RULER,3,Shreyas Singh S,54.5,73.41,1200,1.0,...,0.041271,1.0,50.00,55.250000,13.0,44.0,6.81,5.0,0,0.262586
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
98227,9985,2018-11-18,MUMBAI,TIMELESS DEEDS,4,J Chinoy,54.5,85.01,1400,3.0,...,0.214977,5.0,3.85,56.038462,9.0,26.0,7.69,5.0,0,0.058736
98228,9985,2018-11-18,MUMBAI,COLLEGIUM,4,Dashrath Singh,54.5,85.05,1400,3.0,...,0.143318,4.0,9.09,55.500000,1.0,6.0,0.00,5.0,0,0.088698
98229,9985,2018-11-18,MUMBAI,BOLD MARCH,5,A Prakash,61.0,85.35,1400,3.0,...,0.069867,2.0,22.22,55.444444,NaN,NaN,NaN,2.0,0,0.117454
98230,9985,2018-11-18,MUMBAI,ELEGANT BEAUTY ...,5,Shrikant Kamble,56.0,85.53,1400,3.0,...,0.034396,1.0,9.09,56.590909,18.0,41.0,6.52,5.0,0,0.106164
98231,9985,2018-11-18,MUMBAI,MOUNT MCKINLEY,5,P S Chouhan,53.5,85.87,1400,3.0,...,0.000000,0.0,0.00,55.000000,96.0,134.0,19.70,2.0,0,0.000000

In [97]:

def convert_speed_rating(speed_rating):
    divided_value = speed_rating / 10
    decimal_part = divided_value - int(divided_value)
    speed_rating = round(decimal_part * 1000)
    return speed_rating

In [103]:
data.loc[:, 'Allowance'] = pd.to_numeric(data['Allowance'], errors='coerce')

In [104]:
data['Allowance']

0        0.0
1        0.0
2        0.0
3        0.0
4        0.0
        ...
98227    0.0
98228    0.0
98229   -5.0
98230    0.0
98231    0.0
Name: Allowance, Length: 98232, dtype: object

In [106]:
problematic_rows = data[data['Allowance'].isna()]
print(problematic_rows['Allowance'])

2427     NaN
4511     NaN
4512     NaN
4513     NaN
4514     NaN
        ...
98185    NaN
98186    NaN
98187    NaN
98188    NaN
98189    NaN
Name: Allowance, Length: 20765, dtype: object

In [107]:
data.isnull().sum()

RaceID                    0
Date                      0
Venue                     0
Horse                     0
Age                       0
Jockey                    0
Wt                        0
Time                      0
Dist                      0
Class                   538
Odds                  29138
DistWin                   0
Position                  0
Racing_Incident           0
Allowance             20765
Drawn                    13
Sh                       31
Won By                10856
Rtg                   15705
Present_Rtg               0
Inverse_Pos_Score         0
Win_Probability           0
Normalized_DistWin       31
Probability              31
Total_Top_3               0
Win_PCT                   0
Avg_Wt                    0
Jockey_Top_4          25272
Jockey_Total_Runs     25272
Jockey_Win_Pct        25272
Jockey_Rank               0
Won                       0
Avg_Probability           1
Speed_Rating           9770
dtype: int64

In [108]:
data['Allowance'].fillna(0, inplace=True)

In [109]:
data['Allowance'] = data['Allowance'].astype(float)

In [111]:
data['Allowance']

0        0.0
1        0.0
2        0.0
3        0.0
4        0.0
        ...
98227    0.0
98228    0.0
98229   -5.0
98230    0.0
98231    0.0
Name: Allowance, Length: 98232, dtype: float64

In [115]:

def fill_zero_times(group):
    mean_time = group[group['Time'] > 0]['Time'].mean()
    group['Time'] = group['Time'].replace(0, mean_time)
    return group

data = data.groupby('RaceID').apply(fill_zero_times)

In [117]:
data

              RaceID       Date      Venue  \
RaceID
1      0           1 2024-02-02  BANGALORE
       1           1 2024-02-02  BANGALORE
       2           1 2024-02-02  BANGALORE
       3           1 2024-02-02  BANGALORE
       4           1 2024-02-02  BANGALORE
...              ...        ...        ...
9985   98227    9985 2018-11-18     MUMBAI
       98228    9985 2018-11-18     MUMBAI
       98229    9985 2018-11-18     MUMBAI
       98230    9985 2018-11-18     MUMBAI
       98231    9985 2018-11-18     MUMBAI

                                                          Horse  Age  \
RaceID
1      0                                         EXCELLENT LASS    3
       1                                               POSITANO    3
       2                                             TRUE PUNCH    3
       3                                           SILICON STAR    3
       4                                          AMAZING RULER    3
...                                                         ...  ...
9985   98227                                     TIMELESS DEEDS    4
       98228                                          COLLEGIUM    4
       98229                                         BOLD MARCH    5
       98230  ELEGANT BEAUTY                                ...    5
       98231                                     MOUNT MCKINLEY    5

                       Jockey    Wt   Time  Dist  Class  ... Total_Top_3  \
RaceID                                                   ...
1      0         Neeraj Rawal  53.0  72.20  1200    1.0  ...         2.0
       1             F Norton  54.5  72.25  1200    1.0  ...         1.0
       2         Imran Chisty  54.5  72.86  1200    1.0  ...         2.0
       3               A Ramu  53.0  72.89  1200    1.0  ...         2.0
       4      Shreyas Singh S  54.5  73.41  1200    1.0  ...         1.0
...                       ...   ...    ...   ...    ...  ...         ...
9985   98227         J Chinoy  54.5  85.01  1400    3.0  ...         5.0
       98228   Dashrath Singh  54.5  85.05  1400    3.0  ...         4.0
       98229        A Prakash  61.0  85.35  1400    3.0  ...         2.0
       98230  Shrikant Kamble  56.0  85.53  1400    3.0  ...         1.0
       98231      P S Chouhan  53.5  85.87  1400    3.0  ...         0.0

              Win_PCT     Avg_Wt  Jockey_Top_4  Jockey_Total_Runs  \
RaceID
1      0       100.00  53.750000         138.0              206.0
       1         0.00  54.500000          23.0               38.0
       2         0.00  55.250000         101.0              158.0
       3         0.00  54.000000          11.0               33.0
       4        50.00  55.250000          13.0               44.0
...               ...        ...           ...                ...
9985   98227     3.85  56.038462           9.0               26.0
       98228     9.09  55.500000           1.0                6.0
       98229    22.22  55.444444           NaN                NaN
       98230     9.09  56.590909          18.0               41.0
       98231     0.00  55.000000          96.0              134.0

             Jockey_Win_Pct Jockey_Rank Won Avg_Probability  Speed_Rating
RaceID
1      0              11.31         4.0   1        0.418630    661.000000
       1              13.26         5.0   0        0.228787    651.000000
       2              15.62         4.0   0        0.111439    646.000000
       3               3.70         5.0   0        0.112609    640.000000
       4               6.81         5.0   0        0.262586    628.000000
...                     ...         ...  ..             ...           ...
9985   98227           7.69         5.0   0        0.058736    643.153846
       98228           0.00         5.0   0        0.088698    640.000000
       98229            NaN         2.0   0        0.117454    627.777778
       98230           6.52         5.0   0        0.106164    629.363636
       98231          19.70         2.0   0        0.000000    646.000000

[98232 rows x 34 columns]

In [119]:
data.isnull().sum()

RaceID                    0
Date                      0
Venue                     0
Horse                     0
Age                       0
Jockey                    0
Wt                        0
Time                   8066
Dist                      0
Class                   538
Odds                  29138
DistWin                   0
Position                  0
Racing_Incident           0
Allowance                 0
Drawn                    13
Sh                       31
Won By                10856
Rtg                   15705
Present_Rtg               0
Inverse_Pos_Score         0
Win_Probability           0
Normalized_DistWin       31
Probability              31
Total_Top_3               0
Win_PCT                   0
Avg_Wt                    0
Jockey_Top_4          25272
Jockey_Total_Runs     25272
Jockey_Win_Pct        25272
Jockey_Rank               0
Won                       0
Avg_Probability           1
Speed_Rating           8066
dtype: int64

In [120]:
data.reset_index(drop=True, inplace=True)

In [121]:
data

,RaceID,Date,Venue,Horse,Age,Jockey,Wt,Time,Dist,Class,...,Total_Top_3,Win_PCT,Avg_Wt,Jockey_Top_4,Jockey_Total_Runs,Jockey_Win_Pct,Jockey_Rank,Won,Avg_Probability,Speed_Rating
0,1,2024-02-02,BANGALORE,EXCELLENT LASS,3,Neeraj Rawal,53.0,72.20,1200,1.0,...,2.0,100.00,53.750000,138.0,206.0,11.31,4.0,1,0.418630,661.000000
1,1,2024-02-02,BANGALORE,POSITANO,3,F Norton,54.5,72.25,1200,1.0,...,1.0,0.00,54.500000,23.0,38.0,13.26,5.0,0,0.228787,651.000000
2,1,2024-02-02,BANGALORE,TRUE PUNCH,3,Imran Chisty,54.5,72.86,1200,1.0,...,2.0,0.00,55.250000,101.0,158.0,15.62,4.0,0,0.111439,646.000000
3,1,2024-02-02,BANGALORE,SILICON STAR,3,A Ramu,53.0,72.89,1200,1.0,...,2.0,0.00,54.000000,11.0,33.0,3.70,5.0,0,0.112609,640.000000
4,1,2024-02-02,BANGALORE,AMAZING RULER,3,Shreyas Singh S,54.5,73.41,1200,1.0,...,1.0,50.00,55.250000,13.0,44.0,6.81,5.0,0,0.262586,628.000000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
98227,9985,2018-11-18,MUMBAI,TIMELESS DEEDS,4,J Chinoy,54.5,85.01,1400,3.0,...,5.0,3.85,56.038462,9.0,26.0,7.69,5.0,0,0.058736,643.153846
98228,9985,2018-11-18,MUMBAI,COLLEGIUM,4,Dashrath Singh,54.5,85.05,1400,3.0,...,4.0,9.09,55.500000,1.0,6.0,0.00,5.0,0,0.088698,640.000000
98229,9985,2018-11-18,MUMBAI,BOLD MARCH,5,A Prakash,61.0,85.35,1400,3.0,...,2.0,22.22,55.444444,NaN,NaN,NaN,2.0,0,0.117454,627.777778
98230,9985,2018-11-18,MUMBAI,ELEGANT BEAUTY ...,5,Shrikant Kamble,56.0,85.53,1400,3.0,...,1.0,9.09,56.590909,18.0,41.0,6.52,5.0,0,0.106164,629.363636
98231,9985,2018-11-18,MUMBAI,MOUNT MCKINLEY,5,P S Chouhan,53.5,85.87,1400,3.0,...,0.0,0.00,55.000000,96.0,134.0,19.70,2.0,0,0.000000,646.000000

In [132]:
data['Racing_Incident'].fillna(0, inplace=True)

In [133]:
data = data.sort_values(by=['Horse', 'Date'])

In [134]:
def compute_recent_5_race_stats(group):
    group['Recent_5_Wins'] = group['Won'].rolling(window=5, min_periods=1).sum()  # Calculate rolling sum of wins
    group['Recent_5_Top_3'] = (group['Position'] <= 3).rolling(window=5, min_periods=1).sum()  # Calculate rolling sum of top 3 finishes

    # Calculate racing incidents in last 5 races
    group['Recent_5_Incidents'] = group['Racing_Incident'].rolling(window=5, min_periods=1).sum()

    # Calculate if racing incident in the last race
    group['Incident_Last_Race'] = group['Racing_Incident'].shift(1)

    return group

In [135]:
data = data.groupby('Horse').apply(compute_recent_5_race_stats)

In [136]:
data.reset_index(drop=True, inplace=True)
data

,RaceID,Date,Venue,Horse,Age,Jockey,Wt,Time,Dist,Class,...,Jockey_Total_Runs,Jockey_Win_Pct,Jockey_Rank,Won,Avg_Probability,Speed_Rating,Recent_5_Wins,Recent_5_Top_3,Recent_5_Incidents,Incident_Last_Race
0,9872,2015-03-05,BANGALORE,A CROWN,3,H G Rathod,55.0,72.78,1100,6.0,...,NaN,NaN,3.0,0,0.077847,519.75,0.0,0.0,0.0,NaN
1,4925,2015-06-20,BANGALORE,A CROWN,3,M Kumar,54.0,76.72,1200,4.0,...,NaN,NaN,3.0,0,0.077847,576.75,0.0,0.0,1.0,0.0
2,9869,2015-08-07,BANGALORE,A CROWN,3,S Mallikarjun,58.0,76.92,1200,4.0,...,NaN,NaN,4.0,0,0.077847,552.75,0.0,0.0,1.0,1.0
3,9560,2017-02-03,BANGALORE,A CROWN,5,M Kumar,60.0,88.75,1400,5.0,...,NaN,NaN,3.0,0,0.077847,565.75,0.0,0.0,1.0,0.0
4,6954,2017-08-31,MYSORE,A CROWN,5,Janardhan Paswan,55.5,NaN,1400,5.0,...,NaN,NaN,2.0,1,0.077847,NaN,1.0,1.0,1.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
98227,8551,2015-03-31,KOLKATA,ZURVAN,3,P Kamlesh,56.5,90.18,1400,4.0,...,NaN,NaN,2.0,0,0.051542,563.50,0.0,0.0,3.0,1.0
98228,7231,2016-03-26,KOLKATA,ZURVAN,4,R Rajinder Singh,58.0,88.97,1400,5.0,...,NaN,NaN,3.0,0,0.051542,569.50,0.0,0.0,4.0,0.0
98229,6445,2016-11-09,KOLKATA,ZURVAN,4,Mohit Singh,59.5,77.01,1200,5.0,...,115.0,23.86,5.0,0,0.051542,537.50,0.0,0.0,4.0,1.0
98230,8656,2017-08-26,KOLKATA,ZURVAN,5,Rupal Singh,55.5,89.50,1400,5.0,...,18.0,0.00,5.0,0,0.051542,559.50,0.0,0.0,3.0,1.0
98231,8654,2017-12-26,KOLKATA,ZURVAN,5,Mohit Singh,59.0,102.11,1600,5.0,...,115.0,23.86,5.0,0,0.051542,548.50,0.0,0.0,2.0,0.0

In [137]:
data = data.sort_values(by=['RaceID', 'Date'])
data

,RaceID,Date,Venue,Horse,Age,Jockey,Wt,Time,Dist,Class,...,Jockey_Total_Runs,Jockey_Win_Pct,Jockey_Rank,Won,Avg_Probability,Speed_Rating,Recent_5_Wins,Recent_5_Top_3,Recent_5_Incidents,Incident_Last_Race
3866,1,2024-02-02,BANGALORE,AMAZING RULER,3,Shreyas Singh S,54.5,73.41,1200,1.0,...,44.0,6.81,5.0,0,0.262586,628.000000,0.0,0.0,1.0,NaN
13841,1,2024-02-02,BANGALORE,BOURBONAIRE,3,A Ashok Kumar,54.5,74.19,1200,1.0,...,NaN,NaN,2.0,0,0.005981,627.000000,0.0,0.0,0.0,NaN
13871,1,2024-02-02,BANGALORE,BOWEN,3,Arshad Alam,53.0,73.53,1200,1.0,...,42.0,3.45,5.0,0,0.034705,626.000000,0.0,0.0,1.0,NaN
29443,1,2024-02-02,BANGALORE,EXCELLENT LASS,3,Neeraj Rawal,53.0,72.20,1200,1.0,...,206.0,11.31,4.0,1,0.418630,661.000000,1.0,1.0,0.0,NaN
36582,1,2024-02-02,BANGALORE,GOLDEN STRIDE,3,Surya P,53.0,74.43,1200,1.0,...,30.0,3.33,5.0,0,0.000000,602.000000,0.0,0.0,1.0,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
19181,9985,2018-11-18,MUMBAI,COLLEGIUM,4,Dashrath Singh,54.5,85.05,1400,3.0,...,6.0,0.00,5.0,0,0.088698,640.000000,0.0,2.0,1.0,0.0
27766,9985,2018-11-18,MUMBAI,ELEGANT BEAUTY ...,5,Shrikant Kamble,56.0,85.53,1400,3.0,...,41.0,6.52,5.0,0,0.106164,629.363636,0.0,0.0,0.0,0.0
56376,9985,2018-11-18,MUMBAI,MOUNT MCKINLEY,5,P S Chouhan,53.5,85.87,1400,3.0,...,134.0,19.70,2.0,0,0.000000,646.000000,0.0,0.0,1.0,0.0
81843,9985,2018-11-18,MUMBAI,SPITFIRE,3,Leigh Roche,55.0,84.81,1400,3.0,...,NaN,NaN,2.0,1,0.119113,669.000000,1.0,1.0,0.0,0.0
89639,9985,2018-11-18,MUMBAI,TIMELESS DEEDS,4,J Chinoy,54.5,85.01,1400,3.0,...,26.0,7.69,5.0,0,0.058736,643.153846,0.0,2.0,2.0,0.0

In [146]:
data

,RaceID,Date,Venue,Horse,Age,Jockey,Wt,Time,Dist,Class,...,Jockey_Total_Runs,Jockey_Win_Pct,Jockey_Rank,Won,Avg_Probability,Speed_Rating,Recent_5_Wins,Recent_5_Top_3,Recent_5_Incidents,Incident_Last_Race
0,1,2024-02-02,BANGALORE,AMAZING RULER,3,Shreyas Singh S,54.5,73.41,1200,1.0,...,44.0,6.81,5.0,0,0.262586,628.000000,0.0,0.0,1.0,NaN
1,1,2024-02-02,BANGALORE,BOURBONAIRE,3,A Ashok Kumar,54.5,74.19,1200,1.0,...,NaN,NaN,2.0,0,0.005981,627.000000,0.0,0.0,0.0,NaN
2,1,2024-02-02,BANGALORE,BOWEN,3,Arshad Alam,53.0,73.53,1200,1.0,...,42.0,3.45,5.0,0,0.034705,626.000000,0.0,0.0,1.0,NaN
3,1,2024-02-02,BANGALORE,EXCELLENT LASS,3,Neeraj Rawal,53.0,72.20,1200,1.0,...,206.0,11.31,4.0,1,0.418630,661.000000,1.0,1.0,0.0,NaN
4,1,2024-02-02,BANGALORE,GOLDEN STRIDE,3,Surya P,53.0,74.43,1200,1.0,...,30.0,3.33,5.0,0,0.000000,602.000000,0.0,0.0,1.0,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
98227,9985,2018-11-18,MUMBAI,COLLEGIUM,4,Dashrath Singh,54.5,85.05,1400,3.0,...,6.0,0.00,5.0,0,0.088698,640.000000,0.0,2.0,1.0,0.0
98228,9985,2018-11-18,MUMBAI,ELEGANT BEAUTY ...,5,Shrikant Kamble,56.0,85.53,1400,3.0,...,41.0,6.52,5.0,0,0.106164,629.363636,0.0,0.0,0.0,0.0
98229,9985,2018-11-18,MUMBAI,MOUNT MCKINLEY,5,P S Chouhan,53.5,85.87,1400,3.0,...,134.0,19.70,2.0,0,0.000000,646.000000,0.0,0.0,1.0,0.0
98230,9985,2018-11-18,MUMBAI,SPITFIRE,3,Leigh Roche,55.0,84.81,1400,3.0,...,NaN,NaN,2.0,1,0.119113,669.000000,1.0,1.0,0.0,0.0
98231,9985,2018-11-18,MUMBAI,TIMELESS DEEDS,4,J Chinoy,54.5,85.01,1400,3.0,...,26.0,7.69,5.0,0,0.058736,643.153846,0.0,2.0,2.0,0.0

In [147]:
data['Incident_Last_Race'].fillna(0, inplace=True)

In [148]:
data

,RaceID,Date,Venue,Horse,Age,Jockey,Wt,Time,Dist,Class,...,Jockey_Total_Runs,Jockey_Win_Pct,Jockey_Rank,Won,Avg_Probability,Speed_Rating,Recent_5_Wins,Recent_5_Top_3,Recent_5_Incidents,Incident_Last_Race
0,1,2024-02-02,BANGALORE,AMAZING RULER,3,Shreyas Singh S,54.5,73.41,1200,1.0,...,44.0,6.81,5.0,0,0.262586,628.000000,0.0,0.0,1.0,0.0
1,1,2024-02-02,BANGALORE,BOURBONAIRE,3,A Ashok Kumar,54.5,74.19,1200,1.0,...,NaN,NaN,2.0,0,0.005981,627.000000,0.0,0.0,0.0,0.0
2,1,2024-02-02,BANGALORE,BOWEN,3,Arshad Alam,53.0,73.53,1200,1.0,...,42.0,3.45,5.0,0,0.034705,626.000000,0.0,0.0,1.0,0.0
3,1,2024-02-02,BANGALORE,EXCELLENT LASS,3,Neeraj Rawal,53.0,72.20,1200,1.0,...,206.0,11.31,4.0,1,0.418630,661.000000,1.0,1.0,0.0,0.0
4,1,2024-02-02,BANGALORE,GOLDEN STRIDE,3,Surya P,53.0,74.43,1200,1.0,...,30.0,3.33,5.0,0,0.000000,602.000000,0.0,0.0,1.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
98227,9985,2018-11-18,MUMBAI,COLLEGIUM,4,Dashrath Singh,54.5,85.05,1400,3.0,...,6.0,0.00,5.0,0,0.088698,640.000000,0.0,2.0,1.0,0.0
98228,9985,2018-11-18,MUMBAI,ELEGANT BEAUTY ...,5,Shrikant Kamble,56.0,85.53,1400,3.0,...,41.0,6.52,5.0,0,0.106164,629.363636,0.0,0.0,0.0,0.0
98229,9985,2018-11-18,MUMBAI,MOUNT MCKINLEY,5,P S Chouhan,53.5,85.87,1400,3.0,...,134.0,19.70,2.0,0,0.000000,646.000000,0.0,0.0,1.0,0.0
98230,9985,2018-11-18,MUMBAI,SPITFIRE,3,Leigh Roche,55.0,84.81,1400,3.0,...,NaN,NaN,2.0,1,0.119113,669.000000,1.0,1.0,0.0,0.0
98231,9985,2018-11-18,MUMBAI,TIMELESS DEEDS,4,J Chinoy,54.5,85.01,1400,3.0,...,26.0,7.69,5.0,0,0.058736,643.153846,0.0,2.0,2.0,0.0

In [149]:
data['Recent_5_Incidents'].fillna(0, inplace=True)

In [150]:
def compute_speed_rating(row):
    if row['Time'] > 0:
        base_speed_rating = row['Dist'] / row['Time']
        base_speed_rating = convert_speed_rating(base_speed_rating)

        # Adjustment based on AvgWt - Wt
        weight_diff = row['Avg_Wt'] - row['Wt']
        base_speed_rating += weight_diff * 4

        # Adjustment based on jockey rank
        if row['Jockey_Rank'] == 1:
            base_speed_rating += 12
        elif row['Jockey_Rank'] == 2:
            base_speed_rating += 10
        elif row['Jockey_Rank'] == 4:
            base_speed_rating -= 4
        elif row['Jockey_Rank'] == 5:
            base_speed_rating -= 10

        # Adjustment based on allowance
        base_speed_rating += row['Allowance'] * -4

        # Adjustment based on racing incident in the last race
        if row['Incident_Last_Race'] == 1:
            base_speed_rating += 8

        # Adjustment based on racing incidents in the last 5 races
        if row['Recent_5_Incidents'] >= 3:
            base_speed_rating -= 4

        return base_speed_rating
    else:
        return None

In [151]:
data['Speed_Rating'] = data.apply(compute_speed_rating, axis=1)

In [152]:
data

,RaceID,Date,Venue,Horse,Age,Jockey,Wt,Time,Dist,Class,...,Jockey_Total_Runs,Jockey_Win_Pct,Jockey_Rank,Won,Avg_Probability,Speed_Rating,Recent_5_Wins,Recent_5_Top_3,Recent_5_Incidents,Incident_Last_Race
0,1,2024-02-02,BANGALORE,AMAZING RULER,3,Shreyas Singh S,54.5,73.41,1200,1.0,...,44.0,6.81,5.0,0,0.262586,628.000000,0.0,0.0,1.0,0.0
1,1,2024-02-02,BANGALORE,BOURBONAIRE,3,A Ashok Kumar,54.5,74.19,1200,1.0,...,NaN,NaN,2.0,0,0.005981,627.000000,0.0,0.0,0.0,0.0
2,1,2024-02-02,BANGALORE,BOWEN,3,Arshad Alam,53.0,73.53,1200,1.0,...,42.0,3.45,5.0,0,0.034705,626.000000,0.0,0.0,1.0,0.0
3,1,2024-02-02,BANGALORE,EXCELLENT LASS,3,Neeraj Rawal,53.0,72.20,1200,1.0,...,206.0,11.31,4.0,1,0.418630,661.000000,1.0,1.0,0.0,0.0
4,1,2024-02-02,BANGALORE,GOLDEN STRIDE,3,Surya P,53.0,74.43,1200,1.0,...,30.0,3.33,5.0,0,0.000000,602.000000,0.0,0.0,1.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
98227,9985,2018-11-18,MUMBAI,COLLEGIUM,4,Dashrath Singh,54.5,85.05,1400,3.0,...,6.0,0.00,5.0,0,0.088698,640.000000,0.0,2.0,1.0,0.0
98228,9985,2018-11-18,MUMBAI,ELEGANT BEAUTY ...,5,Shrikant Kamble,56.0,85.53,1400,3.0,...,41.0,6.52,5.0,0,0.106164,629.363636,0.0,0.0,0.0,0.0
98229,9985,2018-11-18,MUMBAI,MOUNT MCKINLEY,5,P S Chouhan,53.5,85.87,1400,3.0,...,134.0,19.70,2.0,0,0.000000,646.000000,0.0,0.0,1.0,0.0
98230,9985,2018-11-18,MUMBAI,SPITFIRE,3,Leigh Roche,55.0,84.81,1400,3.0,...,NaN,NaN,2.0,1,0.119113,669.000000,1.0,1.0,0.0,0.0
98231,9985,2018-11-18,MUMBAI,TIMELESS DEEDS,4,J Chinoy,54.5,85.01,1400,3.0,...,26.0,7.69,5.0,0,0.058736,643.153846,0.0,2.0,2.0,0.0

In [153]:
data.isnull().sum()

RaceID                    0
Date                      0
Venue                     0
Horse                     0
Age                       0
Jockey                    0
Wt                        0
Time                   8066
Dist                      0
Class                   538
Odds                  29138
DistWin                   0
Position                  0
Racing_Incident           0
Allowance                 0
Drawn                    13
Sh                       31
Won By                10856
Rtg                   15705
Present_Rtg               0
Inverse_Pos_Score         0
Win_Probability           0
Normalized_DistWin       31
Probability              31
Total_Top_3               0
Win_PCT                   0
Avg_Wt                    0
Jockey_Top_4          25272
Jockey_Total_Runs     25272
Jockey_Win_Pct        25272
Jockey_Rank               0
Won                       0
Avg_Probability           1
Speed_Rating           8066
Recent_5_Wins             0
Recent_5_Top_3            0
Recent_5_Incidents        0
Incident_Last_Race        0
dtype: int64

In [154]:
def convert_odds(odds):
    try:
        if isinstance(odds, str) and '/' in odds:
            numerator, denominator = map(int, odds.split('/'))
            if denominator == 0:  # Check for zero denominator
                return None  # Handle division by zero
            return numerator / denominator + 1
        elif isinstance(odds, str) and odds.lower() == 'even':
            return 2.0
        elif isinstance(odds, (int, float)):
            return odds + 1
        else:
            return None  # Handle other cases where odds format is not recognized
    except ValueError:
        return None

In [155]:
data.loc[:, 'Decimal_Odds'] = data['Odds'].apply(convert_odds)

In [158]:
def fill_speedrating(group):
    mean_speed_rating = group['Speed_Rating'].mean(skipna=True)
    group['Speed_Rating'] = group['Speed_Rating'].fillna(mean_speed_rating)
    return group

In [159]:
data = data.groupby('Horse').apply(fill_speedrating)

In [163]:
data['Avg_Speed_Rating'] = data.groupby('Horse')['Speed_Rating'].transform('mean')

In [162]:
data.reset_index(drop=True, inplace=True)
data

,RaceID,Date,Venue,Horse,Age,Jockey,Wt,Time,Dist,Class,...,Jockey_Win_Pct,Jockey_Rank,Won,Avg_Probability,Speed_Rating,Recent_5_Wins,Recent_5_Top_3,Recent_5_Incidents,Incident_Last_Race,Decimal_Odds
0,4925,2015-06-20,BANGALORE,A CROWN,3,M Kumar,54.0,76.72,1200,4.0,...,NaN,3.0,0,0.077847,576.750000,0.0,0.0,1.0,0.0,NaN
1,4956,2018-02-11,BANGALORE,A CROWN,6,Sai Kiran,58.5,69.11,1100,4.0,...,NaN,3.0,0,0.077847,586.750000,1.0,2.0,1.0,0.0,NaN
2,6954,2017-08-31,MYSORE,A CROWN,5,Janardhan Paswan,55.5,NaN,1400,5.0,...,NaN,2.0,1,0.077847,562.321429,1.0,1.0,1.0,0.0,NaN
3,9560,2017-02-03,BANGALORE,A CROWN,5,M Kumar,60.0,88.75,1400,5.0,...,NaN,3.0,0,0.077847,565.750000,0.0,0.0,1.0,0.0,NaN
4,9596,2018-06-10,BANGALORE,A CROWN,6,M Naveen,57.0,89.93,1400,4.0,...,66.67,5.0,0,0.077847,567.750000,1.0,2.0,1.0,1.0,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
98227,8551,2015-03-31,KOLKATA,ZURVAN,3,P Kamlesh,56.5,90.18,1400,4.0,...,NaN,2.0,0,0.051542,567.500000,0.0,0.0,3.0,1.0,7.0
98228,8552,2015-03-12,KOLKATA,ZURVAN,3,Vikash Tamang,55.5,87.55,1400,4.0,...,NaN,4.0,0,0.051542,604.500000,0.0,0.0,3.0,1.0,NaN
98229,8554,2014-12-26,KOLKATA,ZURVAN,2,Shrikant Kamble,55.0,87.95,1400,NaN,...,6.52,5.0,0,0.051542,589.500000,0.0,0.0,1.0,0.0,6.5
98230,8654,2017-12-26,KOLKATA,ZURVAN,5,Mohit Singh,59.0,102.11,1600,5.0,...,23.86,5.0,0,0.051542,548.500000,0.0,0.0,2.0,0.0,8.0
98231,8656,2017-08-26,KOLKATA,ZURVAN,5,Rupal Singh,55.5,89.50,1400,5.0,...,0.00,5.0,0,0.051542,579.500000,0.0,0.0,3.0,1.0,13.0

In [169]:
dataset = data.copy()

In [170]:
print(dataset.columns)

Index(['RaceID', 'Date', 'Venue', 'Horse', 'Age', 'Jockey', 'Wt', 'Time',
       'Dist', 'Class', 'Odds', 'DistWin', 'Position', 'Racing_Incident',
       'Allowance', 'Drawn', 'Sh', 'Won By', 'Rtg', 'Present_Rtg',
       'Inverse_Pos_Score', 'Win_Probability', 'Normalized_DistWin',
       'Probability', 'Total_Top_3', 'Win_PCT', 'Avg_Wt', 'Jockey_Top_4',
       'Jockey_Total_Runs', 'Jockey_Win_Pct', 'Jockey_Rank', 'Won',
       'Avg_Probability', 'Speed_Rating', 'Recent_5_Wins', 'Recent_5_Top_3',
       'Recent_5_Incidents', 'Incident_Last_Race', 'Decimal_Odds',
       'Avg_Speed_Rating'],
      dtype='object')

In [165]:
features = ['Age', 'Wt','Avg_Wt' , 'Dist', 'Class', 'Speed_Rating','Avg_Speed_Rating','Win_PCT','Avg_Probability','Decimal_Odds']

In [166]:
target = 'Position'

In [200]:
dataset = dataset[dataset['Position'] <= 19]

# Optionally, reset the index after dropping rows
dataset.reset_index(drop=True, inplace=True)

In [201]:

X = dataset[features]
y = dataset[target]

In [202]:
X_train, X_val, y_train, y_val = train_test_split(X, y, test_size=0.3, random_state=52)

In [203]:
X_train

,Age,Wt,Avg_Wt,Dist,Class,Speed_Rating,Avg_Speed_Rating,Win_PCT,Avg_Probability,Decimal_Odds
48621,4,55.5,56.125000,1400,4.0,545.500000,581.100000,10.00,0.068650,NaN
43511,4,59.0,57.600000,1400,4.0,544.400000,552.650000,0.00,0.049447,NaN
6894,4,60.0,56.452381,1200,4.0,618.809524,617.904762,9.52,0.112201,3.50
50264,4,56.0,56.444444,1400,3.0,593.777778,594.333333,22.22,0.142990,NaN
48958,3,57.0,57.400000,1800,6.0,570.600000,572.800000,0.00,0.017554,NaN
...,...,...,...,...,...,...,...,...,...,...
58268,3,56.0,57.217391,1200,6.0,592.869565,603.956522,8.70,0.073019,NaN
69783,3,54.5,55.571429,1200,6.0,698.285714,709.285714,42.86,0.240978,1.78
56845,4,58.0,55.547619,1200,4.0,653.190476,614.079365,9.52,0.102590,NaN
42652,7,58.5,55.500000,1100,4.0,622.000000,635.100000,10.00,0.101642,NaN
89077,6,60.0,56.735294,2800,1.0,559.941176,586.882353,52.94,0.382896,5.25

In [204]:
X_val

,Age,Wt,Avg_Wt,Dist,Class,Speed_Rating,Avg_Speed_Rating,Win_PCT,Avg_Probability,Decimal_Odds
60480,5,60.0,56.388889,1000,5.0,638.555556,615.000000,0.00,0.055340,NaN
87059,5,54.5,55.357143,1000,4.0,640.428571,648.261905,0.00,0.071632,NaN
3091,4,57.0,57.000000,2800,1.0,511.000000,511.000000,0.00,0.224568,3.0
45969,4,51.5,54.666667,1400,4.0,586.666667,586.666667,0.00,0.000484,NaN
79478,4,61.5,56.705882,1200,3.0,680.823529,658.705882,11.76,0.165673,NaN
...,...,...,...,...,...,...,...,...,...,...
13828,2,56.0,56.000000,1200,6.0,515.000000,515.000000,0.00,0.000000,NaN
63845,5,54.0,56.750000,1400,3.0,610.000000,617.531250,9.38,0.061371,NaN
98023,7,57.0,58.625000,1200,3.0,685.500000,630.750000,0.00,0.046304,NaN
72254,4,57.0,55.838235,1600,4.0,562.352941,575.176471,8.82,0.092375,NaN
67390,5,58.5,54.700000,1400,5.0,484.800000,545.300000,10.00,0.081671,NaN

In [205]:
y_train

48621    10
43511     8
6894      4
50264     8
48958     4
         ..
58268    15
69783     1
56845    11
42652    11
89077     1
Name: Position, Length: 68756, dtype: int64

In [206]:
y_val

60480     4
87059     8
3091      2
45969     8
79478     2
         ..
13828    12
63845     9
98023     6
72254     5
67390    11
Name: Position, Length: 29467, dtype: int64

In [207]:
scaler = StandardScaler()

In [208]:
X_train_scaled = scaler.fit_transform(X_train)

In [209]:
X_train_scaled

array([[-5.28987116e-02, -1.84492931e-01, -3.37453047e-03, ...,
        -1.98224814e-02, -5.26124822e-01,             nan],
       [-5.28987116e-02,  8.38561334e-01,  1.07078540e+00, ...,
        -8.54194730e-01, -8.29751315e-01,             nan],
       [-5.28987116e-02,  1.13086255e+00,  2.35038691e-01, ...,
        -5.98723493e-02,  1.62478206e-01, -6.07233534e-01],
       ...,
       [-5.28987116e-02,  5.46260115e-01, -4.23848757e-01, ...,
        -5.98723493e-02,  1.05140079e-02,             nan],
       [ 1.71572301e-01,  6.92410725e-01, -4.58527044e-01, ...,
        -1.98224814e-02, -4.46099383e-03,             nan],
       [ 9.67486300e-02,  1.13086255e+00,  4.41068512e-01, ...,
         3.56297196e+00,  4.44260164e+00, -3.61501440e-01]])

In [210]:
X_val_scaled = scaler.transform(X_val)

In [211]:
X_val_scaled

array([[ 0.02192496,  1.13086255,  0.18880098, ..., -0.85419473,
        -0.73657592,         nan],
       [ 0.02192496, -0.47679415, -0.5625619 , ..., -0.85419473,
        -0.47897996,         nan],
       [-0.05289871,  0.2539589 ,  0.63383899, ..., -0.85419473,
         1.93918817, -0.6774427 ],
       ...,
       [ 0.1715723 ,  0.2539589 ,  1.81723552, ..., -0.85419473,
        -0.87945552,         nan],
       [-0.05289871,  0.2539589 , -0.21220921, ..., -0.11827841,
        -0.15100181,         nan],
       [ 0.02192496,  0.69241072, -1.04112226, ..., -0.01982248,
        -0.32024502,         nan]])

In [212]:
train_race_ids = dataset.loc[X_train.index, 'RaceID']

In [213]:
train_race_ids

48621    4553
43511    5286
6894     9106
50264    9605
48958    4828
         ...
58268    5854
69783    1366
56845    1981
42652    3860
89077    4699
Name: RaceID, Length: 68756, dtype: int64

In [214]:
val_race_ids = dataset.loc[X_val.index, 'RaceID']

In [215]:
val_race_ids

60480    6118
87059    6069
3091     5313
45969    1605
79478     745
         ...
13828    8255
63845    9909
98023    9925
72254    9817
67390    7980
Name: RaceID, Length: 29467, dtype: int64

In [216]:
train_group = train_race_ids.value_counts().sort_index().values

In [217]:
train_group

array([5, 9, 5, ..., 3, 5, 5])

In [218]:
val_group = val_race_ids.value_counts().sort_index().values

In [219]:
val_group

array([5, 1, 3, ..., 4, 3, 1])

In [220]:
import numpy as np
import lightgbm as lgb
import random

In [221]:
train_data = lgb.Dataset(X_train_scaled, label=y_train, group=train_group)

In [222]:
train_data

In [223]:
val_data = lgb.Dataset(X_val_scaled, label=y_val, group=val_group, reference=train_data)

In [224]:
val_data

In [225]:
params = {
    'objective': 'lambdarank',
    'metric': 'ndcg',
    'ndcg_at': [1, 3, 5],
    'learning_rate': 0.1,
    'num_leaves': 31,
    'min_data_in_leaf': 20,
    'verbose': 1,
    'label_gain': list(range(1, y_train.max() + 2))
}

In [226]:
early_stopping = lgb.early_stopping(stopping_rounds=10)

In [227]:
model = lgb.train(params, train_data, valid_sets=[val_data], callbacks=[early_stopping])

[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.010642 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 1411
[LightGBM] [Info] Number of data points in the train set: 68756, number of used features: 10
Training until validation scores don't improve for 10 rounds
Early stopping, best iteration is:
[89]	valid_0's ndcg@1: 0.903301	valid_0's ndcg@3: 0.953995	valid_0's ndcg@5: 0.968127

In [228]:
random_horses = dataset.loc[X_val.index, 'Horse'].drop_duplicates().sample(n=6, random_state=42)

In [229]:
random_horses

36148    GOLDEN DRAGON
31921        FLAMSTEED
77549       SHIVARATRI
4209     AMOROUS WHITE
13417     BOLD BIDDING
15147         CABERNET
Name: Horse, dtype: object

In [231]:
df_horses_filtered = dataset[dataset['Horse'].isin(random_horses)]
df_horses_filtered.sort_values(by=['Horse', 'Date'], ascending=[True, False], inplace=True)
df_horses_filtered.drop_duplicates(subset='Horse', keep='first', inplace=True)
df_horses_filtered.reset_index(drop=True, inplace=True)
df_horses_filtered

<ipython-input-231-47e6108389c5>:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_horses_filtered.sort_values(by=['Horse', 'Date'], ascending=[True, False], inplace=True)
<ipython-input-231-47e6108389c5>:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_horses_filtered.drop_duplicates(subset='Horse', keep='first', inplace=True)

,RaceID,Date,Venue,Horse,Age,Jockey,Wt,Time,Dist,Class,...,Jockey_Rank,Won,Avg_Probability,Speed_Rating,Recent_5_Wins,Recent_5_Top_3,Recent_5_Incidents,Incident_Last_Race,Decimal_Odds,Avg_Speed_Rating
0,5676,2021-09-11,KOLKATA,AMOROUS WHITE,7,Dharshan Antony B,62.0,70.18,1100,1.0,...,5.0,0,0.228900,559.666667,1.0,2.0,1.0,0.0,NaN,650.333333
1,4637,2022-09-05,HYDERABAD,BOLD BIDDING,4,Abhay Singh,50.5,127.39,2000,3.0,...,5.0,0,0.151463,589.555556,1.0,3.0,3.0,1.0,NaN,595.888889
2,9857,2017-05-22,OOTY,CABERNET,5,Shahar Babu,52.5,79.44,1200,4.0,...,2.0,0,0.030614,539.666667,0.0,0.0,1.0,0.0,NaN,549.333333
3,9366,2017-04-05,KOLKATA,FLAMSTEED,4,C Alford,54.5,84.84,1400,3.0,...,2.0,0,0.282035,671.000000,1.0,2.0,1.0,0.0,3.25,633.000000
4,3837,2024-05-09,DELHI,GOLDEN DRAGON,5,K Sunny Kumar,56.0,66.91,1100,3.0,...,2.0,0,0.130267,654.117647,0.0,3.0,1.0,0.0,NaN,649.294118
5,3821,2022-12-01,CHENNAI,SHIVARATRI,3,Akshay Kumar,52.5,75.25,1200,3.0,...,2.0,0,0.196626,618.200000,2.0,3.0,3.0,1.0,3.75,614.000000

In [232]:

if not df_horses_filtered.empty:
    # Select relevant features and horse names
    X_val_random_features = df_horses_filtered[features]
    horses = df_horses_filtered['Horse']

In [233]:
X_val_random_features

,Age,Wt,Avg_Wt,Dist,Class,Speed_Rating,Avg_Speed_Rating,Win_PCT,Avg_Probability,Decimal_Odds
0,7,62.0,58.666667,1100,1.0,559.666667,650.333333,41.67,0.228900,NaN
1,4,50.5,55.388889,2000,3.0,589.555556,595.888889,22.22,0.151463,NaN
2,5,52.5,57.166667,1200,4.0,539.666667,549.333333,0.00,0.030614,NaN
3,4,54.5,57.250000,1400,3.0,671.000000,633.000000,50.00,0.282035,3.25
4,5,56.0,56.029412,1100,3.0,654.117647,649.294118,11.76,0.130267,NaN
5,3,52.5,54.800000,1200,3.0,618.200000,614.000000,40.00,0.196626,3.75

In [234]:
X_val_random_scaled = scaler.transform(X_val_random_features)

In [235]:
preds_random = model.predict(X_val_random_scaled)

In [236]:
results_random = pd.DataFrame({
        'Horse': horses,  # Include horse names
        'Prediction': preds_random
    })

In [237]:
results_random['Rank'] = results_random['Prediction'].rank(ascending=True)

In [238]:
results_random= results_random.sort_values(by='Rank')

In [240]:
print(results_random[['Horse', 'Rank',]])

           Horse  Rank
3      FLAMSTEED   1.0
5     SHIVARATRI   2.0
1   BOLD BIDDING   3.0
4  GOLDEN DRAGON   4.0
0  AMOROUS WHITE   5.0
2       CABERNET   6.0

In [241]:
selected_horses = ['CZAR', 'MACRON', 'ROMAN SPIRIT', 'SAMURAI BLUE', 'CONSTABLE', 'NEVER GIVE IN']

In [243]:
pred_1 = dataset[dataset['Horse'].isin(selected_horses)]
pred_1 = pred_1.drop_duplicates(subset='Horse', keep='first')

In [244]:
pred_1

,RaceID,Date,Venue,Horse,Age,Jockey,Wt,Time,Dist,Class,...,Jockey_Rank,Won,Avg_Probability,Speed_Rating,Recent_5_Wins,Recent_5_Top_3,Recent_5_Incidents,Incident_Last_Race,Decimal_Odds,Avg_Speed_Rating
19812,1435,2023-12-24,MUMBAI,CONSTABLE,3,Kirtish Bhagat,59.0,73.020833,1200,4.0,...,5.0,0,0.171648,631.000000,0.0,1.0,1.0,0.0,2.10,614.250000
21636,142,2023-08-12,BANGALORE,CZAR,3,Antony Raj S,52.5,84.840000,1400,3.0,...,3.0,0,0.191839,670.181818,1.0,2.0,2.0,1.0,2.90,630.090909
50363,13,2023-03-10,BANGALORE,MACRON,4,A R Pradeep,57.0,88.610000,1400,4.0,...,5.0,0,0.191717,566.600000,0.0,0.0,1.0,0.0,NaN,617.200000
59354,557,2023-12-22,BANGALORE,NEVER GIVE IN,3,S John,60.5,86.600000,1400,4.0,...,4.0,0,0.247310,602.333333,1.0,2.0,0.0,0.0,1.60,636.666667
71228,82,2023-06-04,BANGALORE,ROMAN SPIRIT,3,A Imran Khan,59.0,74.410000,1200,4.0,...,5.0,0,0.186563,599.857143,1.0,1.0,1.0,0.0,3.25,621.571429
73883,1855,2023-01-13,CHENNAI,SAMURAI BLUE,3,Neeraj Rawal,56.0,74.650000,1200,6.0,...,4.0,0,0.149014,607.142857,0.0,0.0,1.0,0.0,5.50,550.285714

In [246]:
pred_1['Decimal_Odds'] = [3.2, 2.8, 4.1, 2.5, 3.7, 3.3]

In [247]:
pred_1

,RaceID,Date,Venue,Horse,Age,Jockey,Wt,Time,Dist,Class,...,Won,Avg_Probability,Speed_Rating,Recent_5_Wins,Recent_5_Top_3,Recent_5_Incidents,Incident_Last_Race,Decimal_Odds,Avg_Speed_Rating,Avg_Odds
19812,1435,2023-12-24,MUMBAI,CONSTABLE,3,Kirtish Bhagat,59.0,73.020833,1200,4.0,...,0,0.171648,631.000000,0.0,1.0,1.0,0.0,3.2,614.250000,3.2
21636,142,2023-08-12,BANGALORE,CZAR,3,Antony Raj S,52.5,84.840000,1400,3.0,...,0,0.191839,670.181818,1.0,2.0,2.0,1.0,2.8,630.090909,2.8
50363,13,2023-03-10,BANGALORE,MACRON,4,A R Pradeep,57.0,88.610000,1400,4.0,...,0,0.191717,566.600000,0.0,0.0,1.0,0.0,4.1,617.200000,4.1
59354,557,2023-12-22,BANGALORE,NEVER GIVE IN,3,S John,60.5,86.600000,1400,4.0,...,0,0.247310,602.333333,1.0,2.0,0.0,0.0,2.5,636.666667,2.5
71228,82,2023-06-04,BANGALORE,ROMAN SPIRIT,3,A Imran Khan,59.0,74.410000,1200,4.0,...,0,0.186563,599.857143,1.0,1.0,1.0,0.0,3.7,621.571429,3.7
73883,1855,2023-01-13,CHENNAI,SAMURAI BLUE,3,Neeraj Rawal,56.0,74.650000,1200,6.0,...,0,0.149014,607.142857,0.0,0.0,1.0,0.0,3.3,550.285714,3.3

In [248]:
if not pred_1.empty:
    # Select relevant features and horse names
    X_val_random_features_1 = pred_1[features]
    horses_1 = pred_1['Horse']

In [249]:
X_val_random_features_1

,Age,Wt,Avg_Wt,Dist,Class,Speed_Rating,Avg_Speed_Rating,Win_PCT,Avg_Probability,Decimal_Odds
19812,3,59.0,57.000000,1200,4.0,631.000000,614.250000,20.00,0.171648,3.2
21636,3,52.5,55.545455,1400,3.0,670.181818,630.090909,27.27,0.191839,2.8
50363,4,57.0,56.150000,1400,4.0,566.600000,617.200000,20.00,0.191717,4.1
59354,3,60.5,57.833333,1400,4.0,602.333333,636.666667,33.33,0.247310,2.5
71228,3,59.0,58.214286,1200,4.0,599.857143,621.571429,28.57,0.186563,3.7
73883,3,56.0,56.785714,1200,6.0,607.142857,550.285714,14.29,0.149014,3.3

In [250]:
X_val_random_scaled_1 = scaler.transform(X_val_random_features_1)

In [251]:
preds_random_1 = model.predict(X_val_random_scaled_1)

In [252]:
results_random_1 = pd.DataFrame({
        'Horse': horses_1,  # Include horse names
        'Prediction': preds_random_1
    })

In [253]:
results_random_1['Rank'] = results_random_1['Prediction'].rank(ascending=True)

In [254]:
results_random_1 = results_random_1.sort_values(by='Rank')

In [255]:
print(results_random_1[['Horse', 'Rank']])

               Horse  Rank
59354  NEVER GIVE IN   1.0
21636           CZAR   2.0
19812      CONSTABLE   3.0
73883   SAMURAI BLUE   4.0
71228   ROMAN SPIRIT   5.0
50363         MACRON   6.0

In [300]:

random_race_id = random.choice(val_race_ids.unique())
random_race_id

7712

In [301]:
df_race_filtered_5 = dataset[dataset['RaceID'] == random_race_id]

In [302]:
df_race_filtered_5

,RaceID,Date,Venue,Horse,Age,Jockey,Wt,Time,Dist,Class,...,Jockey_Rank,Won,Avg_Probability,Speed_Rating,Recent_5_Wins,Recent_5_Top_3,Recent_5_Incidents,Incident_Last_Race,Decimal_Odds,Avg_Speed_Rating
186,7712,2018-11-05,HYDERABAD,AAROHI,3,B R Kumar,54.5,76.10,1200,6.0,...,5.0,0,0.054063,566.294118,0.0,1.0,0.0,0.0,NaN,569.823529
1994,7712,2018-11-05,HYDERABAD,AIR SALUTE,3,C Umesh,54.5,75.11,1200,6.0,...,3.0,0,0.086919,614.105263,0.0,4.0,2.0,1.0,NaN,602.315789
2214,7712,2018-11-05,HYDERABAD,AJMAL BIRJU,3,A M Tograllu,56.0,76.48,1200,6.0,...,5.0,0,0.092269,555.545455,0.0,0.0,0.0,0.0,NaN,582.727273
25011,7712,2018-11-05,HYDERABAD,DIESIS DREAM,3,Ajit Singh,54.5,77.26,1200,6.0,...,2.0,0,0.078879,571.142857,0.0,0.0,1.0,1.0,NaN,565.321429
38471,7712,2018-11-05,HYDERABAD,HANDSOME DUO,3,G Naresh,56.0,76.23,1200,6.0,...,5.0,0,0.086289,561.555556,0.0,1.0,0.0,0.0,NaN,574.888889
49264,7712,2018-11-05,HYDERABAD,LOCKHART,3,P Sai Kumar,56.0,75.41,1200,6.0,...,4.0,0,0.096545,585.327273,0.0,3.0,1.0,0.0,NaN,593.290909
59402,7712,2018-11-05,HYDERABAD,NEW DESIRE,3,Md Ismail,54.5,78.27,1200,6.0,...,5.0,0,0.020523,531.000000,0.0,0.0,1.0,1.0,NaN,571.500000
63018,7712,2018-11-05,HYDERABAD,PARIZAAT,3,Nakhat Singh,54.5,75.94,1200,6.0,...,4.0,0,0.051498,587.250000,0.0,0.0,3.0,1.0,NaN,553.250000
80834,7712,2018-11-05,HYDERABAD,SOUTHERN STATE,3,Kiran Naidu,54.5,74.22,1200,6.0,...,5.0,1,0.097481,617.285714,1.0,2.0,0.0,0.0,NaN,620.857143
96256,7712,2018-11-05,HYDERABAD,WINGS OF EAGLES,3,Arshad Alam,56.0,75.76,1200,6.0,...,5.0,0,0.087079,572.782609,0.0,2.0,0.0,0.0,3.75,583.260870

In [303]:
column_names = ['Position', 'Horse']

In [304]:

Actual_Position = df_race_filtered_5[column_names]
Actual_Position

       Position            Horse
186           6           AAROHI
1994          2       AIR SALUTE
2214          8      AJMAL BIRJU
25011         9     DIESIS DREAM
38471         7     HANDSOME DUO
49264         3         LOCKHART
59402        10       NEW DESIRE
63018         5         PARIZAAT
80834         1   SOUTHERN STATE
96256         4  WINGS OF EAGLES

In [305]:

if not df_race_filtered_5.empty:
    # Select relevant features and horse names
    X_val_race_features_5 = df_race_filtered_5[features]
    horses_5 = df_race_filtered_5['Horse']

In [306]:
X_val_race_features_5

,Age,Wt,Avg_Wt,Dist,Class,Speed_Rating,Avg_Speed_Rating,Win_PCT,Avg_Probability,Decimal_Odds
186,3,54.5,54.323529,1200,6.0,566.294118,569.823529,5.88,0.054063,NaN
1994,3,54.5,56.526316,1200,6.0,614.105263,602.315789,0.00,0.086919,NaN
2214,3,56.0,55.136364,1200,6.0,555.545455,582.727273,9.09,0.092269,NaN
25011,3,54.5,54.535714,1200,6.0,571.142857,565.321429,7.14,0.078879,NaN
38471,3,56.0,55.388889,1200,6.0,561.555556,574.888889,5.56,0.086289,NaN
49264,3,56.0,55.581818,1200,6.0,585.327273,593.290909,7.27,0.096545,NaN
59402,3,54.5,54.500000,1200,6.0,531.000000,571.500000,0.00,0.020523,NaN
63018,3,54.5,56.312500,1200,6.0,587.250000,553.250000,0.00,0.051498,NaN
80834,3,54.5,57.071429,1200,6.0,617.285714,620.857143,7.14,0.097481,NaN
96256,3,56.0,55.695652,1200,6.0,572.782609,583.260870,4.35,0.087079,3.75

In [307]:
horses_5

186               AAROHI
1994          AIR SALUTE
2214         AJMAL BIRJU
25011       DIESIS DREAM
38471       HANDSOME DUO
49264           LOCKHART
59402         NEW DESIRE
63018           PARIZAAT
80834     SOUTHERN STATE
96256    WINGS OF EAGLES
Name: Horse, dtype: object

In [308]:
X_val_race_scaled_5 = scaler.transform(X_val_race_features_5)

In [309]:
preds_race_5 = model.predict(X_val_race_scaled_5)

In [310]:
results_race_5 = pd.DataFrame({
        'Horse': horses_5,  # Include horse names
        'Prediction': preds_race_5
    })

In [311]:
results_race_5['Rank'] = results_race_5['Prediction'].rank(ascending=True)

In [312]:
results_race_5 = results_race_5.sort_values(by='Rank')

In [313]:
results_race_5 = pd.merge(results_race_5, Actual_Position, on='Horse', how='inner')

In [314]:
print(results_race_5[['Horse', 'Rank', 'Position',]])

             Horse  Rank  Position
0  WINGS OF EAGLES   1.0         4
1       AIR SALUTE   2.0         2
2   SOUTHERN STATE   3.0         1
3         LOCKHART   4.0         3
4         PARIZAAT   5.0         5
5     DIESIS DREAM   6.0         9
6     HANDSOME DUO   7.0         7
7      AJMAL BIRJU   8.0         8
8           AAROHI   9.0         6
9       NEW DESIRE  10.0        10