<a href="https://colab.research.google.com/github/Anand3074/Anand3074/blob/main/SpeedRating_based__Ranking_1_got_some_error.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from google.colab import drive

In [3]:
drive.mount('/content/drive')

Mounted at /content/drive

In [4]:
df = pd.read_csv('/content/drive/My Drive/Current_Dataset/Race_Result_1_7_24.csv', low_memory=False)
df

,RaceID,Date,Venue,Horse,Age,Trainer,Jockey,Wt,Time,Dist,...,Odds,DistWin,Position,Racing_Incident,Allowance,Drawn,Sh,Won By,Rtg,Present_Rtg
0,1,02 Feb 2024,BANGALORE,EXCELLENT LASS,3,Rajesh Narredu,Neeraj Rawal,53,72.20,1200,...,3,NaN,1,1,NaN,1,A,Lnk,NaN,0.0
1,1,02 Feb 2024,BANGALORE,POSITANO,3,S S Attaollahi,F Norton,54.5,72.25,1200,...,7/4,NaN,2,0,NaN,9,A,3 3/4,NaN,0.0
2,1,02 Feb 2024,BANGALORE,TRUE PUNCH,3,M Rajendra Singh,Imran Chisty,54.5,72.86,1200,...,10,3.75,3,0,NaN,7,A,Snk,NaN,0.0
3,1,02 Feb 2024,BANGALORE,SILICON STAR,3,Warren Singh,A Ramu,53,72.89,1200,...,9,3.75,4,1,NaN,4,A,3 1/4,NaN,0.0
4,1,02 Feb 2024,BANGALORE,AMAZING RULER,3,B Prithviraj,Shreyas Singh S,54.5,73.41,1200,...,15,7.00,5,1,NaN,12,A,3/4,NaN,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
382769,39459,19 Mar 2024,KOLKATA,TIGER SHARK,4,Neil Darashah,Neeraj Rawal,55.5,126.90,2000,...,5/2,2.50,2,0,NaN,4,A,3 1/2,46,50.0
382770,39459,19 Mar 2024,KOLKATA,LUCKY NINE,4,B Rajender Reddy,P Uday Kiran,53.5,127.45,2000,...,5/2,6.00,3,0,NaN,3,A,2 1/2,42,44.0
382771,39459,19 Mar 2024,KOLKATA,OH MY DARLING ...,4,P Quinn,P S Chouhan,60,127.80,2000,...,5,8.50,4,0,NaN,1,A,Dist,NaN,55.0
382772,39459,19 Mar 2024,KOLKATA,WHISTLE BLOWER,6,Shafiq Khan,N S Parmar,53,131.99,2000,...,8,8.50,5,0,NaN,6,S,1/2,NaN,41.0
382773,39459,19 Mar 2024,KOLKATA,TEAM PLAYER,7,B Rajender Reddy,Nikhil Naidu,59.5,132.08,2000,...,12,9.00,6,0,NaN,5,A,NaN,NaN,54.0

In [5]:
tf = pd.read_csv('/content/drive/My Drive/Current_Dataset/TrackWork_Dataset.csv', low_memory=False)
tf

,Date,Venue,Horses,Change,Distance,Surface,Horse Name,Age_Color_Sex,Pedigree,Rating,Trainer,Bred At,Owner
0,NaN,NaN,NaN,NaN,NaN,NaN,MEZCAL,"6Y, b m",Western Aristocrat(USA) / Amber Valley(GB),63.0,Bharath Singh,Manju Stud,"Mr Joydeep Datta Gupta, Mr Marthand Singh Mahi..."
1,28 May 2024,OOT,"Vandhiyathevan (C Umesh),\n ...",(-3),800M,Outer Sand,VANDHIYATHEVAN,"3Y, dkb c",Kingda Ka(AUS) / Siyouni,0.0,K S Mandanna,Star Born Stud,"Mr T Dhevanathan Yadav, Mrs Meenakshi Yadav, M..."
2,15 May 2024,OOT,Vandhiyathevan(Darshan Antony\n)\n ...,(-1),800m,Outer Sand,VANDHIYATHEVAN,"3Y, dkb c",Kingda Ka(AUS) / Siyouni,0.0,K S Mandanna,Star Born Stud,"Mr T Dhevanathan Yadav, Mrs Meenakshi Yadav, M..."
3,07 May 2024,OOT,"Vandhiyathevan (Darshan Antony),\n ...",(-1),1300m,Gate Practice,VANDHIYATHEVAN,"3Y, dkb c",Kingda Ka(AUS) / Siyouni,0.0,K S Mandanna,Star Born Stud,"Mr T Dhevanathan Yadav, Mrs Meenakshi Yadav, M..."
4,23 Apr 2024,OOT,"Krishvi (Ram Nandan Manjhi),\n ...",(-1),1300m,Gate Practice,VANDHIYATHEVAN,"3Y, dkb c",Kingda Ka(AUS) / Siyouni,0.0,K S Mandanna,Star Born Stud,"Mr T Dhevanathan Yadav, Mrs Meenakshi Yadav, M..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...
38633,20 Dec 2023,CHE,Crown Angel(C.A. Brisson\n)\n ...,(-1),1000M,Outer Sand,Own,"54Y, -",- /,0.0,-,NaN,-
38634,19 Dec 2023,KOL,Queenstown(J H Arul\n)\n ...,(+4),800m,Outer Sand,Own,"54Y, -",- /,0.0,-,NaN,-
38635,18 Dec 2023,MUM,"Own Voice (Dashrath),\n ...",(-12),800M,Race Grass,Own,"54Y, -",- /,0.0,-,NaN,-
38636,15 Dec 2023,CHE,"Kings Walk (A.M. Tograllu),\n ...",(-10),1000M,Outer Sand,Own,"54Y, -",- /,0.0,-,NaN,-
38637,15 Dec 2023,CHE,"Multicrown (Ram Nandan. M),\n ...",(-4),1000M,Outer Sand,Own,"54Y, -",- /,0.0,-,NaN,-

In [6]:
jf = pd.read_csv('/content/drive/My Drive/Current_Dataset/Jockey_Ranking.csv', low_memory=False)
jf

            Trainer  Top 4  Total Runs   Win% RANKING  JO5KEY_RANK
0           VIVEK G    213         316  21.42       A            2
1       P SAI KUMAR    122         236  10.66       B            4
2          P TREVOR    186         221  28.63      A+            1
3       HINDU SINGH    137         219  19.73       C            5
4       KOSHI KUMAR     90         213  12.68       D            5
..              ...    ...         ...    ...     ...          ...
233     S P RANJANE      0           1   0.00       C            5
234  MUDASSAR NAZAR      0           1   0.00       C            5
235    NAVEEN KUMAR      0           1   0.00       C            5
236             NDS      0           0   0.00       C            5
237       WITHDRAWN      0           0   0.00       C            5

[238 rows x 6 columns]

In [7]:
data = df.copy()

In [8]:
Track = tf.copy()

In [9]:
data['DistWin'] = data['DistWin'].fillna(0)

In [10]:
data['Allowance'] = data['Allowance'].fillna(0)
data['Allowance'] = pd.to_numeric(data['Allowance'], errors='coerce')

In [11]:
data['Allowance']

0         0.0
1         0.0
2         0.0
3         0.0
4         0.0
         ...
382769    0.0
382770    0.0
382771    0.0
382772    0.0
382773    0.0
Name: Allowance, Length: 382774, dtype: float64

In [12]:
data['DistWin']

0         0.00
1         0.00
2         3.75
3         3.75
4         7.00
          ...
382769    2.50
382770    6.00
382771    8.50
382772    8.50
382773    9.00
Name: DistWin, Length: 382774, dtype: float64

In [13]:
horse_performance_metrics = data.groupby('Horse').apply(
    lambda x: pd.Series({
        'Top_3': (x['Position'] <= 3).sum(),
        'Win_PCT': round((x['Position'] == 1).mean() * 100, 2)
    })
).reset_index()

In [14]:
data = data.merge(horse_performance_metrics, on='Horse', how='left')

In [15]:
data.loc[data['Position'] == 1, 'Racing_Incident'] = 0

In [16]:
data['Won'] = (data['Position'] == 1).astype(int)

In [17]:
def compute_recent_5_race_stats(group):
    group['Recent_Wins'] = group['Won'].rolling(window=5, min_periods=1).sum()
    group['Recent_Top_3'] = (group['Position'] <= 3).rolling(window=5, min_periods=1).sum()
    group['Recent_Incidents'] = group['Racing_Incident'].rolling(window=5, min_periods=1).sum()
    group['Incident_Last_Race'] = group['Racing_Incident'].shift(1)
    return group

In [18]:
data = data.sort_values(by=['Horse', 'Date'])

In [19]:
data = data.groupby('Horse').apply(compute_recent_5_race_stats)

In [20]:
data.reset_index(drop=True, inplace=True)

In [21]:
data

,RaceID,Date,Venue,Horse,Age,Trainer,Jockey,Wt,Time,Dist,...,Won By,Rtg,Present_Rtg,Top_3,Win_PCT,Won,Recent_Wins,Recent_Top_3,Recent_Incidents,Incident_Last_Race
0,35611,02 Feb 2008,HYDERABAD,16562,38,NaN,Lkk,54.5,97.71,1400,...,3 1/2,16,NaN,0.0,0.00,0,0.0,0.0,0.0,NaN
1,35466,31 Dec 2007,HYDERABAD,16562,37,NaN,A Ramana,52,90.47,1400,...,1/2,14,NaN,0.0,0.00,0,0.0,0.0,0.0,0.0
2,34517,17 Oct 2008,MYSORE,17056,38,NaN,Harish,60,128.19,2000,...,1 1/2,103,NaN,1.0,100.00,1,1.0,1.0,0.0,NaN
3,37728,15 Dec 2007,KOLKATA,17639,37,NaN,Suraj Narredu,51,86.94,1400,...,NaN,48,NaN,4.0,66.67,1,1.0,1.0,0.0,NaN
4,30710,15 Mar 2008,KOLKATA,17639,38,NaN,C Alford,54,101.53,1600,...,NaN,74,NaN,4.0,66.67,1,2.0,2.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
382769,38418,23 Jan 2011,HYDERABAD,ZYCON,5,T Srinagesh,Daniel M Grant,55.5,67.41,1100,...,3/4,89,88.0,13.0,25.00,0,0.0,1.0,1.0,0.0
382770,30564,23 Jul 2009,HYDERABAD,ZYCON,3,T Srinagesh,M F Ali Khan,51,74.24,1200,...,1 3/4,NaN,88.0,13.0,25.00,1,1.0,2.0,1.0,1.0
382771,35810,24 Aug 2009,HYDERABAD,ZYCON,3,T Srinagesh,M F Ali Khan,57,63.03,1000,...,1 1/2,65,88.0,13.0,25.00,0,1.0,3.0,1.0,0.0
382772,36394,24 Nov 2009,HYDERABAD,ZYCON,3,T Srinagesh,C Ruzaan,59,59.90,1000,...,3/4,84,88.0,13.0,25.00,1,2.0,3.0,1.0,0.0
382773,15547,26 Dec 2010,HYDERABAD,ZYCON,4,T Srinagesh,Nitin Singh,52,74.31,1200,...,3/4,89,88.0,13.0,25.00,0,2.0,3.0,2.0,0.0

In [22]:
data['Incident_Last_Race'] = data['Incident_Last_Race'].fillna(0)

In [23]:
Jockey = jf.copy()

In [24]:
Jockey = Jockey.rename(columns={'JO5KEY_RANK': 'Jockey_Rank'})

In [25]:
Jockey = Jockey.rename(columns={'Trainer': 'Jockey'})

In [26]:
Jockey = Jockey.drop(['RANKING', "Win%", 'Total Runs', 'Top 4'], axis=1)
Jockey['Jockey'] = Jockey['Jockey'].str.title()

In [27]:
Jockey

             Jockey  Jockey_Rank
0           Vivek G            2
1       P Sai Kumar            4
2          P Trevor            1
3       Hindu Singh            5
4       Koshi Kumar            5
..              ...          ...
233     S P Ranjane            5
234  Mudassar Nazar            5
235    Naveen Kumar            5
236             Nds            5
237       Withdrawn            5

[238 rows x 2 columns]

In [28]:
data = data.merge(Jockey, on='Jockey', how='left')

In [29]:
data.isnull().sum()

RaceID                     0
Date                       0
Venue                      0
Horse                      0
Age                        0
Trainer                  204
Jockey                     3
Wt                         0
Time                       0
Dist                       0
Class                   2526
Odds                  136228
DistWin                    0
Position                   0
Racing_Incident            0
Allowance             154693
Drawn                     28
Sh                       322
Won By                 43173
Rtg                    56683
Present_Rtg               93
Top_3                      0
Win_PCT                    0
Won                        0
Recent_Wins                0
Recent_Top_3               0
Recent_Incidents           0
Incident_Last_Race         0
Jockey_Rank           188513
dtype: int64

In [30]:
import random
data['Jockey_Rank'] = data['Jockey_Rank'].fillna(5)

In [31]:
data['Allowance'] = data['Allowance'].fillna(0)

In [32]:
data.isnull().sum()

RaceID                     0
Date                       0
Venue                      0
Horse                      0
Age                        0
Trainer                  204
Jockey                     3
Wt                         0
Time                       0
Dist                       0
Class                   2526
Odds                  136228
DistWin                    0
Position                   0
Racing_Incident            0
Allowance                  0
Drawn                     28
Sh                       322
Won By                 43173
Rtg                    56683
Present_Rtg               93
Top_3                      0
Win_PCT                    0
Won                        0
Recent_Wins                0
Recent_Top_3               0
Recent_Incidents           0
Incident_Last_Race         0
Jockey_Rank                0
dtype: int64

In [33]:
data['Rtg'] = data['Rtg'].fillna(0)

In [34]:
data['Rtg'] = pd.to_numeric(data['Rtg'], errors='coerce')

In [35]:
data['Rtg']

0          16.0
1          14.0
2         103.0
3          48.0
4          74.0
          ...
382769     89.0
382770      0.0
382771     65.0
382772     84.0
382773     89.0
Name: Rtg, Length: 382774, dtype: float64

In [36]:
# data = pd.DataFrame(data)
# # Export DataFrame to CSV
# data.to_csv('Future_Op_Data.csv', index=False)
# # Download the CSV file
# from google.colab import files
# # files.download('Future_Op_Data.csv')

In [37]:
data

,RaceID,Date,Venue,Horse,Age,Trainer,Jockey,Wt,Time,Dist,...,Rtg,Present_Rtg,Top_3,Win_PCT,Won,Recent_Wins,Recent_Top_3,Recent_Incidents,Incident_Last_Race,Jockey_Rank
0,35611,02 Feb 2008,HYDERABAD,16562,38,NaN,Lkk,54.5,97.71,1400,...,16.0,NaN,0.0,0.00,0,0.0,0.0,0.0,0.0,5.0
1,35466,31 Dec 2007,HYDERABAD,16562,37,NaN,A Ramana,52,90.47,1400,...,14.0,NaN,0.0,0.00,0,0.0,0.0,0.0,0.0,5.0
2,34517,17 Oct 2008,MYSORE,17056,38,NaN,Harish,60,128.19,2000,...,103.0,NaN,1.0,100.00,1,1.0,1.0,0.0,0.0,5.0
3,37728,15 Dec 2007,KOLKATA,17639,37,NaN,Suraj Narredu,51,86.94,1400,...,48.0,NaN,4.0,66.67,1,1.0,1.0,0.0,0.0,1.0
4,30710,15 Mar 2008,KOLKATA,17639,38,NaN,C Alford,54,101.53,1600,...,74.0,NaN,4.0,66.67,1,2.0,2.0,0.0,0.0,5.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
382769,38418,23 Jan 2011,HYDERABAD,ZYCON,5,T Srinagesh,Daniel M Grant,55.5,67.41,1100,...,89.0,88.0,13.0,25.00,0,0.0,1.0,1.0,0.0,5.0
382770,30564,23 Jul 2009,HYDERABAD,ZYCON,3,T Srinagesh,M F Ali Khan,51,74.24,1200,...,0.0,88.0,13.0,25.00,1,1.0,2.0,1.0,1.0,5.0
382771,35810,24 Aug 2009,HYDERABAD,ZYCON,3,T Srinagesh,M F Ali Khan,57,63.03,1000,...,65.0,88.0,13.0,25.00,0,1.0,3.0,1.0,0.0,5.0
382772,36394,24 Nov 2009,HYDERABAD,ZYCON,3,T Srinagesh,C Ruzaan,59,59.90,1000,...,84.0,88.0,13.0,25.00,1,2.0,3.0,1.0,0.0,5.0
382773,15547,26 Dec 2010,HYDERABAD,ZYCON,4,T Srinagesh,Nitin Singh,52,74.31,1200,...,89.0,88.0,13.0,25.00,0,2.0,3.0,2.0,0.0,5.0

In [38]:
# import numpy as np
# data['Jockey_Rank'] = np.ceil(data['Jockey_Rank'])

In [39]:
data

,RaceID,Date,Venue,Horse,Age,Trainer,Jockey,Wt,Time,Dist,...,Rtg,Present_Rtg,Top_3,Win_PCT,Won,Recent_Wins,Recent_Top_3,Recent_Incidents,Incident_Last_Race,Jockey_Rank
0,35611,02 Feb 2008,HYDERABAD,16562,38,NaN,Lkk,54.5,97.71,1400,...,16.0,NaN,0.0,0.00,0,0.0,0.0,0.0,0.0,5.0
1,35466,31 Dec 2007,HYDERABAD,16562,37,NaN,A Ramana,52,90.47,1400,...,14.0,NaN,0.0,0.00,0,0.0,0.0,0.0,0.0,5.0
2,34517,17 Oct 2008,MYSORE,17056,38,NaN,Harish,60,128.19,2000,...,103.0,NaN,1.0,100.00,1,1.0,1.0,0.0,0.0,5.0
3,37728,15 Dec 2007,KOLKATA,17639,37,NaN,Suraj Narredu,51,86.94,1400,...,48.0,NaN,4.0,66.67,1,1.0,1.0,0.0,0.0,1.0
4,30710,15 Mar 2008,KOLKATA,17639,38,NaN,C Alford,54,101.53,1600,...,74.0,NaN,4.0,66.67,1,2.0,2.0,0.0,0.0,5.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
382769,38418,23 Jan 2011,HYDERABAD,ZYCON,5,T Srinagesh,Daniel M Grant,55.5,67.41,1100,...,89.0,88.0,13.0,25.00,0,0.0,1.0,1.0,0.0,5.0
382770,30564,23 Jul 2009,HYDERABAD,ZYCON,3,T Srinagesh,M F Ali Khan,51,74.24,1200,...,0.0,88.0,13.0,25.00,1,1.0,2.0,1.0,1.0,5.0
382771,35810,24 Aug 2009,HYDERABAD,ZYCON,3,T Srinagesh,M F Ali Khan,57,63.03,1000,...,65.0,88.0,13.0,25.00,0,1.0,3.0,1.0,0.0,5.0
382772,36394,24 Nov 2009,HYDERABAD,ZYCON,3,T Srinagesh,C Ruzaan,59,59.90,1000,...,84.0,88.0,13.0,25.00,1,2.0,3.0,1.0,0.0,5.0
382773,15547,26 Dec 2010,HYDERABAD,ZYCON,4,T Srinagesh,Nitin Singh,52,74.31,1200,...,89.0,88.0,13.0,25.00,0,2.0,3.0,2.0,0.0,5.0

In [40]:
data = data.sort_values(by=['RaceID', 'Position'])
data

,RaceID,Date,Venue,Horse,Age,Trainer,Jockey,Wt,Time,Dist,...,Rtg,Present_Rtg,Top_3,Win_PCT,Won,Recent_Wins,Recent_Top_3,Recent_Incidents,Incident_Last_Race,Jockey_Rank
114349,1,02 Feb 2024,BANGALORE,EXCELLENT LASS,3,Rajesh Narredu,Neeraj Rawal,53,72.20,1200,...,0.0,0.0,2.0,100.00,1,1.0,1.0,0.0,0.0,4.0
251715,1,02 Feb 2024,BANGALORE,POSITANO,3,S S Attaollahi,F Norton,54.5,72.25,1200,...,0.0,0.0,1.0,0.00,0,0.0,1.0,0.0,0.0,5.0
356179,1,02 Feb 2024,BANGALORE,TRUE PUNCH,3,M Rajendra Singh,Imran Chisty,54.5,72.86,1200,...,0.0,0.0,2.0,0.00,0,0.0,1.0,0.0,0.0,4.0
303559,1,02 Feb 2024,BANGALORE,SILICON STAR,3,Warren Singh,A Ramu,53,72.89,1200,...,0.0,0.0,2.0,0.00,0,0.0,0.0,1.0,0.0,5.0
17111,1,02 Feb 2024,BANGALORE,AMAZING RULER,3,B Prithviraj,Shreyas Singh S,54.5,73.41,1200,...,0.0,0.0,1.0,50.00,0,0.0,0.0,1.0,0.0,5.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
349102,39459,19 Mar 2024,KOLKATA,TIGER SHARK,4,Neil Darashah,Neeraj Rawal,55.5,126.90,2000,...,46.0,50.0,5.0,10.00,0,0.0,2.0,2.0,0.0,4.0
196025,39459,19 Mar 2024,KOLKATA,LUCKY NINE,4,B Rajender Reddy,P Uday Kiran,53.5,127.45,2000,...,42.0,44.0,5.0,10.53,0,0.0,1.0,2.0,0.0,5.0
236307,39459,19 Mar 2024,KOLKATA,OH MY DARLING ...,4,P Quinn,P S Chouhan,60,127.80,2000,...,0.0,55.0,4.0,25.00,0,1.0,3.0,0.0,0.0,2.0
370976,39459,19 Mar 2024,KOLKATA,WHISTLE BLOWER,6,Shafiq Khan,N S Parmar,53,131.99,2000,...,0.0,41.0,9.0,5.88,0,0.0,1.0,0.0,0.0,4.0
342387,39459,19 Mar 2024,KOLKATA,TEAM PLAYER,7,B Rajender Reddy,Nikhil Naidu,59.5,132.08,2000,...,0.0,54.0,12.0,7.14,0,0.0,1.0,1.0,0.0,5.0

In [41]:
trackwork = tf.copy()

In [42]:
trackwork

,Date,Venue,Horses,Change,Distance,Surface,Horse Name,Age_Color_Sex,Pedigree,Rating,Trainer,Bred At,Owner
0,NaN,NaN,NaN,NaN,NaN,NaN,MEZCAL,"6Y, b m",Western Aristocrat(USA) / Amber Valley(GB),63.0,Bharath Singh,Manju Stud,"Mr Joydeep Datta Gupta, Mr Marthand Singh Mahi..."
1,28 May 2024,OOT,"Vandhiyathevan (C Umesh),\n ...",(-3),800M,Outer Sand,VANDHIYATHEVAN,"3Y, dkb c",Kingda Ka(AUS) / Siyouni,0.0,K S Mandanna,Star Born Stud,"Mr T Dhevanathan Yadav, Mrs Meenakshi Yadav, M..."
2,15 May 2024,OOT,Vandhiyathevan(Darshan Antony\n)\n ...,(-1),800m,Outer Sand,VANDHIYATHEVAN,"3Y, dkb c",Kingda Ka(AUS) / Siyouni,0.0,K S Mandanna,Star Born Stud,"Mr T Dhevanathan Yadav, Mrs Meenakshi Yadav, M..."
3,07 May 2024,OOT,"Vandhiyathevan (Darshan Antony),\n ...",(-1),1300m,Gate Practice,VANDHIYATHEVAN,"3Y, dkb c",Kingda Ka(AUS) / Siyouni,0.0,K S Mandanna,Star Born Stud,"Mr T Dhevanathan Yadav, Mrs Meenakshi Yadav, M..."
4,23 Apr 2024,OOT,"Krishvi (Ram Nandan Manjhi),\n ...",(-1),1300m,Gate Practice,VANDHIYATHEVAN,"3Y, dkb c",Kingda Ka(AUS) / Siyouni,0.0,K S Mandanna,Star Born Stud,"Mr T Dhevanathan Yadav, Mrs Meenakshi Yadav, M..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...
38633,20 Dec 2023,CHE,Crown Angel(C.A. Brisson\n)\n ...,(-1),1000M,Outer Sand,Own,"54Y, -",- /,0.0,-,NaN,-
38634,19 Dec 2023,KOL,Queenstown(J H Arul\n)\n ...,(+4),800m,Outer Sand,Own,"54Y, -",- /,0.0,-,NaN,-
38635,18 Dec 2023,MUM,"Own Voice (Dashrath),\n ...",(-12),800M,Race Grass,Own,"54Y, -",- /,0.0,-,NaN,-
38636,15 Dec 2023,CHE,"Kings Walk (A.M. Tograllu),\n ...",(-10),1000M,Outer Sand,Own,"54Y, -",- /,0.0,-,NaN,-
38637,15 Dec 2023,CHE,"Multicrown (Ram Nandan. M),\n ...",(-4),1000M,Outer Sand,Own,"54Y, -",- /,0.0,-,NaN,-

In [43]:
trackwork = trackwork.drop(['Horses', "Age_Color_Sex", 'Pedigree','Venue', 'Rating',	'Trainer',	'Bred At',	'Owner'], axis=1)
trackwork

              Date Change Distance        Surface      Horse Name
0              NaN    NaN      NaN            NaN          MEZCAL
1      28 May 2024   (-3)     800M     Outer Sand  VANDHIYATHEVAN
2      15 May 2024   (-1)     800m     Outer Sand  VANDHIYATHEVAN
3      07 May 2024   (-1)    1300m  Gate Practice  VANDHIYATHEVAN
4      23 Apr 2024   (-1)    1300m  Gate Practice  VANDHIYATHEVAN
...            ...    ...      ...            ...             ...
38633  20 Dec 2023   (-1)    1000M     Outer Sand             Own
38634  19 Dec 2023   (+4)     800m     Outer Sand             Own
38635  18 Dec 2023  (-12)     800M     Race Grass             Own
38636  15 Dec 2023  (-10)    1000M     Outer Sand             Own
38637  15 Dec 2023   (-4)    1000M     Outer Sand             Own

[38638 rows x 5 columns]

In [44]:
trackwork = trackwork.rename(columns={'Date': 'Trackwork_Date'})

In [45]:
# trackwork = trackwork.rename(columns={'Venue': 'Trackwork_Venue',})

In [46]:
trackwork = trackwork.rename(columns={'Horse Name': 'Horse'})

In [47]:
Track_Data = data.copy()

In [48]:
Track_Data

,RaceID,Date,Venue,Horse,Age,Trainer,Jockey,Wt,Time,Dist,...,Rtg,Present_Rtg,Top_3,Win_PCT,Won,Recent_Wins,Recent_Top_3,Recent_Incidents,Incident_Last_Race,Jockey_Rank
114349,1,02 Feb 2024,BANGALORE,EXCELLENT LASS,3,Rajesh Narredu,Neeraj Rawal,53,72.20,1200,...,0.0,0.0,2.0,100.00,1,1.0,1.0,0.0,0.0,4.0
251715,1,02 Feb 2024,BANGALORE,POSITANO,3,S S Attaollahi,F Norton,54.5,72.25,1200,...,0.0,0.0,1.0,0.00,0,0.0,1.0,0.0,0.0,5.0
356179,1,02 Feb 2024,BANGALORE,TRUE PUNCH,3,M Rajendra Singh,Imran Chisty,54.5,72.86,1200,...,0.0,0.0,2.0,0.00,0,0.0,1.0,0.0,0.0,4.0
303559,1,02 Feb 2024,BANGALORE,SILICON STAR,3,Warren Singh,A Ramu,53,72.89,1200,...,0.0,0.0,2.0,0.00,0,0.0,0.0,1.0,0.0,5.0
17111,1,02 Feb 2024,BANGALORE,AMAZING RULER,3,B Prithviraj,Shreyas Singh S,54.5,73.41,1200,...,0.0,0.0,1.0,50.00,0,0.0,0.0,1.0,0.0,5.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
349102,39459,19 Mar 2024,KOLKATA,TIGER SHARK,4,Neil Darashah,Neeraj Rawal,55.5,126.90,2000,...,46.0,50.0,5.0,10.00,0,0.0,2.0,2.0,0.0,4.0
196025,39459,19 Mar 2024,KOLKATA,LUCKY NINE,4,B Rajender Reddy,P Uday Kiran,53.5,127.45,2000,...,42.0,44.0,5.0,10.53,0,0.0,1.0,2.0,0.0,5.0
236307,39459,19 Mar 2024,KOLKATA,OH MY DARLING ...,4,P Quinn,P S Chouhan,60,127.80,2000,...,0.0,55.0,4.0,25.00,0,1.0,3.0,0.0,0.0,2.0
370976,39459,19 Mar 2024,KOLKATA,WHISTLE BLOWER,6,Shafiq Khan,N S Parmar,53,131.99,2000,...,0.0,41.0,9.0,5.88,0,0.0,1.0,0.0,0.0,4.0
342387,39459,19 Mar 2024,KOLKATA,TEAM PLAYER,7,B Rajender Reddy,Nikhil Naidu,59.5,132.08,2000,...,0.0,54.0,12.0,7.14,0,0.0,1.0,1.0,0.0,5.0

In [49]:
format_string = '%d %b %Y'  # Day, Month abbreviation, Year
trackwork['Trackwork_Date'] = pd.to_datetime(trackwork['Trackwork_Date'], format=format_string)
Track_Data['Date'] = pd.to_datetime(Track_Data['Date'], format=format_string)

In [50]:
# trackwork = trackwork.fillna(0)

In [51]:
trackwork

      Trackwork_Date Change Distance        Surface           Horse
0                NaT    NaN      NaN            NaN          MEZCAL
1         2024-05-28   (-3)     800M     Outer Sand  VANDHIYATHEVAN
2         2024-05-15   (-1)     800m     Outer Sand  VANDHIYATHEVAN
3         2024-05-07   (-1)    1300m  Gate Practice  VANDHIYATHEVAN
4         2024-04-23   (-1)    1300m  Gate Practice  VANDHIYATHEVAN
...              ...    ...      ...            ...             ...
38633     2023-12-20   (-1)    1000M     Outer Sand             Own
38634     2023-12-19   (+4)     800m     Outer Sand             Own
38635     2023-12-18  (-12)     800M     Race Grass             Own
38636     2023-12-15  (-10)    1000M     Outer Sand             Own
38637     2023-12-15   (-4)    1000M     Outer Sand             Own

[38638 rows x 5 columns]

In [52]:
# trackwork.dropna(subset=['Trackwork_Date'], inplace=True)

In [53]:
trackwork

      Trackwork_Date Change Distance        Surface           Horse
0                NaT    NaN      NaN            NaN          MEZCAL
1         2024-05-28   (-3)     800M     Outer Sand  VANDHIYATHEVAN
2         2024-05-15   (-1)     800m     Outer Sand  VANDHIYATHEVAN
3         2024-05-07   (-1)    1300m  Gate Practice  VANDHIYATHEVAN
4         2024-04-23   (-1)    1300m  Gate Practice  VANDHIYATHEVAN
...              ...    ...      ...            ...             ...
38633     2023-12-20   (-1)    1000M     Outer Sand             Own
38634     2023-12-19   (+4)     800m     Outer Sand             Own
38635     2023-12-18  (-12)     800M     Race Grass             Own
38636     2023-12-15  (-10)    1000M     Outer Sand             Own
38637     2023-12-15   (-4)    1000M     Outer Sand             Own

[38638 rows x 5 columns]

In [54]:
# trackwork['Horse'] = trackwork['Horse'].str.title()

In [55]:
trackwork

      Trackwork_Date Change Distance        Surface           Horse
0                NaT    NaN      NaN            NaN          MEZCAL
1         2024-05-28   (-3)     800M     Outer Sand  VANDHIYATHEVAN
2         2024-05-15   (-1)     800m     Outer Sand  VANDHIYATHEVAN
3         2024-05-07   (-1)    1300m  Gate Practice  VANDHIYATHEVAN
4         2024-04-23   (-1)    1300m  Gate Practice  VANDHIYATHEVAN
...              ...    ...      ...            ...             ...
38633     2023-12-20   (-1)    1000M     Outer Sand             Own
38634     2023-12-19   (+4)     800m     Outer Sand             Own
38635     2023-12-18  (-12)     800M     Race Grass             Own
38636     2023-12-15  (-10)    1000M     Outer Sand             Own
38637     2023-12-15   (-4)    1000M     Outer Sand             Own

[38638 rows x 5 columns]

In [56]:
# Track_Data['Date'] = pd.to_datetime(Track_Data['Date'], format=format_string)
# trackwork['Trackwork_Date'] = pd.to_datetime(trackwork['Trackwork_Date'], format=format_string)

In [57]:
Track_Data

,RaceID,Date,Venue,Horse,Age,Trainer,Jockey,Wt,Time,Dist,...,Rtg,Present_Rtg,Top_3,Win_PCT,Won,Recent_Wins,Recent_Top_3,Recent_Incidents,Incident_Last_Race,Jockey_Rank
114349,1,2024-02-02,BANGALORE,EXCELLENT LASS,3,Rajesh Narredu,Neeraj Rawal,53,72.20,1200,...,0.0,0.0,2.0,100.00,1,1.0,1.0,0.0,0.0,4.0
251715,1,2024-02-02,BANGALORE,POSITANO,3,S S Attaollahi,F Norton,54.5,72.25,1200,...,0.0,0.0,1.0,0.00,0,0.0,1.0,0.0,0.0,5.0
356179,1,2024-02-02,BANGALORE,TRUE PUNCH,3,M Rajendra Singh,Imran Chisty,54.5,72.86,1200,...,0.0,0.0,2.0,0.00,0,0.0,1.0,0.0,0.0,4.0
303559,1,2024-02-02,BANGALORE,SILICON STAR,3,Warren Singh,A Ramu,53,72.89,1200,...,0.0,0.0,2.0,0.00,0,0.0,0.0,1.0,0.0,5.0
17111,1,2024-02-02,BANGALORE,AMAZING RULER,3,B Prithviraj,Shreyas Singh S,54.5,73.41,1200,...,0.0,0.0,1.0,50.00,0,0.0,0.0,1.0,0.0,5.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
349102,39459,2024-03-19,KOLKATA,TIGER SHARK,4,Neil Darashah,Neeraj Rawal,55.5,126.90,2000,...,46.0,50.0,5.0,10.00,0,0.0,2.0,2.0,0.0,4.0
196025,39459,2024-03-19,KOLKATA,LUCKY NINE,4,B Rajender Reddy,P Uday Kiran,53.5,127.45,2000,...,42.0,44.0,5.0,10.53,0,0.0,1.0,2.0,0.0,5.0
236307,39459,2024-03-19,KOLKATA,OH MY DARLING ...,4,P Quinn,P S Chouhan,60,127.80,2000,...,0.0,55.0,4.0,25.00,0,1.0,3.0,0.0,0.0,2.0
370976,39459,2024-03-19,KOLKATA,WHISTLE BLOWER,6,Shafiq Khan,N S Parmar,53,131.99,2000,...,0.0,41.0,9.0,5.88,0,0.0,1.0,0.0,0.0,4.0
342387,39459,2024-03-19,KOLKATA,TEAM PLAYER,7,B Rajender Reddy,Nikhil Naidu,59.5,132.08,2000,...,0.0,54.0,12.0,7.14,0,0.0,1.0,1.0,0.0,5.0

In [58]:
trackwork

      Trackwork_Date Change Distance        Surface           Horse
0                NaT    NaN      NaN            NaN          MEZCAL
1         2024-05-28   (-3)     800M     Outer Sand  VANDHIYATHEVAN
2         2024-05-15   (-1)     800m     Outer Sand  VANDHIYATHEVAN
3         2024-05-07   (-1)    1300m  Gate Practice  VANDHIYATHEVAN
4         2024-04-23   (-1)    1300m  Gate Practice  VANDHIYATHEVAN
...              ...    ...      ...            ...             ...
38633     2023-12-20   (-1)    1000M     Outer Sand             Own
38634     2023-12-19   (+4)     800m     Outer Sand             Own
38635     2023-12-18  (-12)     800M     Race Grass             Own
38636     2023-12-15  (-10)    1000M     Outer Sand             Own
38637     2023-12-15   (-4)    1000M     Outer Sand             Own

[38638 rows x 5 columns]

In [59]:
Track_Data_1 = data.copy()

In [60]:
# Track_Data_1['Time'] = pd.to_numeric(Track_Data_1['Time'], errors='coerce')

# # Replace 0 or 0.0 values with NaN to facilitate mean calculation
# Track_Data_1.loc[Track_Data_1['Time'] == 0, 'Time'] = pd.NA

# # Calculate mean time for each RaceID group, excluding NaN values
# mean_time_per_race = Track_Data_1.groupby('RaceID')['Time'].mean()

In [61]:
# race_ids_with_nan_mean = mean_time_per_race[mean_time_per_race.isna()].index

In [62]:
# Track_Data_1 = Track_Data_1[~Track_Data_1['RaceID'].isin(race_ids_with_nan_mean)]

In [63]:
# Track_Data_1.isnull().sum()

In [64]:
# def fill_time_with_mean(row):
#     if pd.isna(row['Time']):
#         return mean_time_per_race[row['RaceID']]
#     return row['Time']

In [65]:
# Track_Data_1.loc['Time'] = Track_Data_1.apply(fill_time_with_mean, axis=1)

In [66]:
# Track_Data_1.isnull().sum()

In [67]:
Track_Data_1

,RaceID,Date,Venue,Horse,Age,Trainer,Jockey,Wt,Time,Dist,...,Rtg,Present_Rtg,Top_3,Win_PCT,Won,Recent_Wins,Recent_Top_3,Recent_Incidents,Incident_Last_Race,Jockey_Rank
114349,1,02 Feb 2024,BANGALORE,EXCELLENT LASS,3,Rajesh Narredu,Neeraj Rawal,53,72.20,1200,...,0.0,0.0,2.0,100.00,1,1.0,1.0,0.0,0.0,4.0
251715,1,02 Feb 2024,BANGALORE,POSITANO,3,S S Attaollahi,F Norton,54.5,72.25,1200,...,0.0,0.0,1.0,0.00,0,0.0,1.0,0.0,0.0,5.0
356179,1,02 Feb 2024,BANGALORE,TRUE PUNCH,3,M Rajendra Singh,Imran Chisty,54.5,72.86,1200,...,0.0,0.0,2.0,0.00,0,0.0,1.0,0.0,0.0,4.0
303559,1,02 Feb 2024,BANGALORE,SILICON STAR,3,Warren Singh,A Ramu,53,72.89,1200,...,0.0,0.0,2.0,0.00,0,0.0,0.0,1.0,0.0,5.0
17111,1,02 Feb 2024,BANGALORE,AMAZING RULER,3,B Prithviraj,Shreyas Singh S,54.5,73.41,1200,...,0.0,0.0,1.0,50.00,0,0.0,0.0,1.0,0.0,5.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
349102,39459,19 Mar 2024,KOLKATA,TIGER SHARK,4,Neil Darashah,Neeraj Rawal,55.5,126.90,2000,...,46.0,50.0,5.0,10.00,0,0.0,2.0,2.0,0.0,4.0
196025,39459,19 Mar 2024,KOLKATA,LUCKY NINE,4,B Rajender Reddy,P Uday Kiran,53.5,127.45,2000,...,42.0,44.0,5.0,10.53,0,0.0,1.0,2.0,0.0,5.0
236307,39459,19 Mar 2024,KOLKATA,OH MY DARLING ...,4,P Quinn,P S Chouhan,60,127.80,2000,...,0.0,55.0,4.0,25.00,0,1.0,3.0,0.0,0.0,2.0
370976,39459,19 Mar 2024,KOLKATA,WHISTLE BLOWER,6,Shafiq Khan,N S Parmar,53,131.99,2000,...,0.0,41.0,9.0,5.88,0,0.0,1.0,0.0,0.0,4.0
342387,39459,19 Mar 2024,KOLKATA,TEAM PLAYER,7,B Rajender Reddy,Nikhil Naidu,59.5,132.08,2000,...,0.0,54.0,12.0,7.14,0,0.0,1.0,1.0,0.0,5.0

In [68]:
def convert_speed_rating(speed_rating):
    divided_value = speed_rating / 10
    decimal_part = divided_value - int(divided_value)
    speed_rating = round(decimal_part * 1000)
    return speed_rating

In [69]:
def compute_speed_rating(row):
    if row['Time'] > 0:
        base_speed_rating = row['Dist'] / row['Time']
        base_speed_rating = convert_speed_rating(base_speed_rating)

        # Adjustment based on jockey rank
        if row['Jockey_Rank'] == 1:
            base_speed_rating += 12
        elif row['Jockey_Rank'] == 2:
            base_speed_rating += 10
        elif row['Jockey_Rank'] == 4:
            base_speed_rating -= 4
        elif row['Jockey_Rank'] == 5:
            base_speed_rating -= 10

        # Adjustment based on allowance
        base_speed_rating += row['Allowance'] * -4

        # Adjustment based on racing incident in the last race
        if row['Incident_Last_Race'] == 1:
            base_speed_rating += 12

        # Adjustment based on racing incidents in the last 5 races
        if row['Recent_Incidents'] >= 3:
            base_speed_rating -= 4

        # Adjustment based on Sh column
        if row['Sh'] == 'A':
            base_speed_rating += 15
        elif row['Sh'] == 'S':
            base_speed_rating -= 15

        return base_speed_rating
    else:
        return None

In [70]:
Track_Data_1['Speed_Rating'] = Track_Data_1.apply(compute_speed_rating, axis=1)

In [71]:
Track_Data_1

,RaceID,Date,Venue,Horse,Age,Trainer,Jockey,Wt,Time,Dist,...,Present_Rtg,Top_3,Win_PCT,Won,Recent_Wins,Recent_Top_3,Recent_Incidents,Incident_Last_Race,Jockey_Rank,Speed_Rating
114349,1,02 Feb 2024,BANGALORE,EXCELLENT LASS,3,Rajesh Narredu,Neeraj Rawal,53,72.20,1200,...,0.0,2.0,100.00,1,1.0,1.0,0.0,0.0,4.0,673.0
251715,1,02 Feb 2024,BANGALORE,POSITANO,3,S S Attaollahi,F Norton,54.5,72.25,1200,...,0.0,1.0,0.00,0,0.0,1.0,0.0,0.0,5.0,666.0
356179,1,02 Feb 2024,BANGALORE,TRUE PUNCH,3,M Rajendra Singh,Imran Chisty,54.5,72.86,1200,...,0.0,2.0,0.00,0,0.0,1.0,0.0,0.0,4.0,658.0
303559,1,02 Feb 2024,BANGALORE,SILICON STAR,3,Warren Singh,A Ramu,53,72.89,1200,...,0.0,2.0,0.00,0,0.0,0.0,1.0,0.0,5.0,651.0
17111,1,02 Feb 2024,BANGALORE,AMAZING RULER,3,B Prithviraj,Shreyas Singh S,54.5,73.41,1200,...,0.0,1.0,50.00,0,0.0,0.0,1.0,0.0,5.0,640.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
349102,39459,19 Mar 2024,KOLKATA,TIGER SHARK,4,Neil Darashah,Neeraj Rawal,55.5,126.90,2000,...,50.0,5.0,10.00,0,0.0,2.0,2.0,0.0,4.0,587.0
196025,39459,19 Mar 2024,KOLKATA,LUCKY NINE,4,B Rajender Reddy,P Uday Kiran,53.5,127.45,2000,...,44.0,5.0,10.53,0,0.0,1.0,2.0,0.0,5.0,574.0
236307,39459,19 Mar 2024,KOLKATA,OH MY DARLING ...,4,P Quinn,P S Chouhan,60,127.80,2000,...,55.0,4.0,25.00,0,1.0,3.0,0.0,0.0,2.0,590.0
370976,39459,19 Mar 2024,KOLKATA,WHISTLE BLOWER,6,Shafiq Khan,N S Parmar,53,131.99,2000,...,41.0,9.0,5.88,0,0.0,1.0,0.0,0.0,4.0,496.0
342387,39459,19 Mar 2024,KOLKATA,TEAM PLAYER,7,B Rajender Reddy,Nikhil Naidu,59.5,132.08,2000,...,54.0,12.0,7.14,0,0.0,1.0,1.0,0.0,5.0,519.0

In [72]:
def predict_speed_rating(row, prev_row):
    if pd.isna(prev_row['Speed_Rating']):
        return None

    predicted_rating = prev_row['Speed_Rating']

    # Adjust for distance change
    dist_diff = row['Dist'] - prev_row['Dist']
    predicted_rating += (dist_diff // 100) * -10

    # Adjust for weight change
    wt_diff = row['Wt'] - prev_row['Wt']
    predicted_rating += wt_diff * -4

    # Adjust for jockey rank change
    if row['Jockey_Rank'] == 1:
            predicted_rating += 12
    elif row['Jockey_Rank'] == 2:
            predicted_rating += 10
    elif row['Jockey_Rank'] == 4:
            predicted_rating -= 4
    elif row['Jockey_Rank'] == 5:
            predicted_rating -= 10

        # Adjustment based on allowance
    predicted_rating += row['Allowance'] * -4
    if prev_row['Incident_Last_Race'] == 1:
            predicted_rating += 12

        # Adjustment based on racing incidents in the last 5 races
    if row['Recent_Incidents'] >= 3:
            predicted_rating -= 4

    if row['Sh'] == 'A':
            predicted_rating += 15
    elif row['Sh'] == 'S':
            predicted_rating -= 15
    return predicted_rating

In [73]:
Track_Data_1 = Track_Data_1.sort_values(by=['Horse', 'Date'])

In [74]:
# row_to_remove = 'Time'  # Replace with the actual index value if different

# # Select and remove the row using 'loc' for exact index matching
# Track_Data_1 = Track_Data_1.loc[Track_Data_1.index != row_to_remove]

In [75]:
Track_Data_1

,RaceID,Date,Venue,Horse,Age,Trainer,Jockey,Wt,Time,Dist,...,Present_Rtg,Top_3,Win_PCT,Won,Recent_Wins,Recent_Top_3,Recent_Incidents,Incident_Last_Race,Jockey_Rank,Speed_Rating
0,35611,02 Feb 2008,HYDERABAD,16562,38,NaN,Lkk,54.5,97.71,1400,...,NaN,0.0,0.00,0,0.0,0.0,0.0,0.0,5.0,408.0
1,35466,31 Dec 2007,HYDERABAD,16562,37,NaN,A Ramana,52,90.47,1400,...,NaN,0.0,0.00,0,0.0,0.0,0.0,0.0,5.0,528.0
2,34517,17 Oct 2008,MYSORE,17056,38,NaN,Harish,60,128.19,2000,...,NaN,1.0,100.00,1,1.0,1.0,0.0,0.0,5.0,565.0
3,37728,15 Dec 2007,KOLKATA,17639,37,NaN,Suraj Narredu,51,86.94,1400,...,NaN,4.0,66.67,1,1.0,1.0,0.0,0.0,1.0,607.0
4,30710,15 Mar 2008,KOLKATA,17639,38,NaN,C Alford,54,101.53,1600,...,NaN,4.0,66.67,1,2.0,2.0,0.0,0.0,5.0,551.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
382769,38418,23 Jan 2011,HYDERABAD,ZYCON,5,T Srinagesh,Daniel M Grant,55.5,67.41,1100,...,88.0,13.0,25.00,0,0.0,1.0,1.0,0.0,5.0,637.0
382770,30564,23 Jul 2009,HYDERABAD,ZYCON,3,T Srinagesh,M F Ali Khan,51,74.24,1200,...,88.0,13.0,25.00,1,1.0,2.0,1.0,1.0,5.0,633.0
382771,35810,24 Aug 2009,HYDERABAD,ZYCON,3,T Srinagesh,M F Ali Khan,57,63.03,1000,...,88.0,13.0,25.00,0,1.0,3.0,1.0,0.0,5.0,592.0
382772,36394,24 Nov 2009,HYDERABAD,ZYCON,3,T Srinagesh,C Ruzaan,59,59.90,1000,...,88.0,13.0,25.00,1,2.0,3.0,1.0,0.0,5.0,674.0
382773,15547,26 Dec 2010,HYDERABAD,ZYCON,4,T Srinagesh,Nitin Singh,52,74.31,1200,...,88.0,13.0,25.00,0,2.0,3.0,2.0,0.0,5.0,620.0

In [76]:
Track_Data_1['Wt'] = pd.to_numeric(Track_Data_1['Wt'], errors='coerce')

In [77]:
Track_Data_1['Wt'] = Track_Data_1['Wt'].fillna(Track_Data_1['Wt'].mean())

In [78]:
Track_Data_1['Wt']

0         54.5
1         52.0
2         60.0
3         51.0
4         54.0
          ...
382769    55.5
382770    51.0
382771    57.0
382772    59.0
382773    52.0
Name: Wt, Length: 382774, dtype: float64

In [79]:
Track_Data_1['Predicted_Speed_Rating'] = Track_Data_1.groupby('Horse').apply(
    lambda x: x.assign(Predicted_Speed_Rating=x.apply(
        lambda row: predict_speed_rating(row, x.shift(1).loc[row.name]), axis=1
    ))
).reset_index(level=0, drop=True)['Predicted_Speed_Rating']

In [80]:
Track_Data_1

,RaceID,Date,Venue,Horse,Age,Trainer,Jockey,Wt,Time,Dist,...,Top_3,Win_PCT,Won,Recent_Wins,Recent_Top_3,Recent_Incidents,Incident_Last_Race,Jockey_Rank,Speed_Rating,Predicted_Speed_Rating
0,35611,02 Feb 2008,HYDERABAD,16562,38,NaN,Lkk,54.5,97.71,1400,...,0.0,0.00,0,0.0,0.0,0.0,0.0,5.0,408.0,NaN
1,35466,31 Dec 2007,HYDERABAD,16562,37,NaN,A Ramana,52.0,90.47,1400,...,0.0,0.00,0,0.0,0.0,0.0,0.0,5.0,528.0,399.0
2,34517,17 Oct 2008,MYSORE,17056,38,NaN,Harish,60.0,128.19,2000,...,1.0,100.00,1,1.0,1.0,0.0,0.0,5.0,565.0,NaN
3,37728,15 Dec 2007,KOLKATA,17639,37,NaN,Suraj Narredu,51.0,86.94,1400,...,4.0,66.67,1,1.0,1.0,0.0,0.0,1.0,607.0,NaN
4,30710,15 Mar 2008,KOLKATA,17639,38,NaN,C Alford,54.0,101.53,1600,...,4.0,66.67,1,2.0,2.0,0.0,0.0,5.0,551.0,550.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
382769,38418,23 Jan 2011,HYDERABAD,ZYCON,5,T Srinagesh,Daniel M Grant,55.5,67.41,1100,...,13.0,25.00,0,0.0,1.0,1.0,0.0,5.0,637.0,627.0
382770,30564,23 Jul 2009,HYDERABAD,ZYCON,3,T Srinagesh,M F Ali Khan,51.0,74.24,1200,...,13.0,25.00,1,1.0,2.0,1.0,1.0,5.0,633.0,650.0
382771,35810,24 Aug 2009,HYDERABAD,ZYCON,3,T Srinagesh,M F Ali Khan,57.0,63.03,1000,...,13.0,25.00,0,1.0,3.0,1.0,0.0,5.0,592.0,646.0
382772,36394,24 Nov 2009,HYDERABAD,ZYCON,3,T Srinagesh,C Ruzaan,59.0,59.90,1000,...,13.0,25.00,1,2.0,3.0,1.0,0.0,5.0,674.0,589.0
382773,15547,26 Dec 2010,HYDERABAD,ZYCON,4,T Srinagesh,Nitin Singh,52.0,74.31,1200,...,13.0,25.00,0,2.0,3.0,2.0,0.0,5.0,620.0,687.0

In [81]:
# Track_Data_1 = Track_Data_1.sort_values(by=['Horse', 'Date'])

In [82]:
horse_data = Track_Data_1[Track_Data_1['Horse'] == 'MANSA MUSA']
horse_data

,RaceID,Date,Venue,Horse,Age,Trainer,Jockey,Wt,Time,Dist,...,Top_3,Win_PCT,Won,Recent_Wins,Recent_Top_3,Recent_Incidents,Incident_Last_Race,Jockey_Rank,Speed_Rating,Predicted_Speed_Rating
202296,1514,07 Apr 2024,MUMBAI,MANSA MUSA,3,P Shroff,P Trevor,56.0,96.35,1600,...,1.0,0.0,0,0.0,1.0,1.0,0.0,1.0,688.0,NaN
202297,1517,18 Feb 2024,MUMBAI,MANSA MUSA,3,P Shroff,P Trevor,56.0,100.39,1600,...,1.0,0.0,0,0.0,1.0,2.0,1.0,1.0,633.0,715.0

In [83]:
print(Track_Data_1.columns)

Index(['RaceID', 'Date', 'Venue', 'Horse', 'Age', 'Trainer', 'Jockey', 'Wt',
       'Time', 'Dist', 'Class', 'Odds', 'DistWin', 'Position',
       'Racing_Incident', 'Allowance', 'Drawn', 'Sh', 'Won By', 'Rtg',
       'Present_Rtg', 'Top_3', 'Win_PCT', 'Won', 'Recent_Wins', 'Recent_Top_3',
       'Recent_Incidents', 'Incident_Last_Race', 'Jockey_Rank', 'Speed_Rating',
       'Predicted_Speed_Rating'],
      dtype='object')

In [84]:
features = ['Wt','Dist','Age', 'Class', 'Rtg', 'Top_3', 'Win_PCT', 'Recent_Wins', 'Recent_Top_3','Predicted_Speed_Rating',]

In [85]:
target= 'Position'

In [86]:
race_ids_with_nan = Track_Data_1[Track_Data_1['Predicted_Speed_Rating'].isna()]['RaceID'].unique()

In [87]:
Track_Data_2 = Track_Data_1[~Track_Data_1['RaceID'].isin(race_ids_with_nan)]

In [88]:
Track_Data_2

,RaceID,Date,Venue,Horse,Age,Trainer,Jockey,Wt,Time,Dist,...,Top_3,Win_PCT,Won,Recent_Wins,Recent_Top_3,Recent_Incidents,Incident_Last_Race,Jockey_Rank,Speed_Rating,Predicted_Speed_Rating
4,30710,15 Mar 2008,KOLKATA,17639,38,NaN,C Alford,54.0,101.53,1600,...,4.0,66.67,1,2.0,2.0,0.0,0.0,5.0,551.0,550.0
5,37094,16 Feb 2008,KOLKATA,17639,38,NaN,Neeraj Rawal,48.0,0.00,1600,...,4.0,66.67,1,3.0,3.0,0.0,0.0,4.0,NaN,556.0
7,36427,29 Jul 2007,BANGALORE,17639,37,NaN,S John,56.0,71.10,1100,...,4.0,66.67,0,3.0,3.0,0.0,0.0,4.0,558.0,616.0
8,37780,30 Jul 2008,KOLKATA,17639,38,NaN,C Alford,57.5,91.03,1400,...,4.0,66.67,1,3.0,3.0,0.0,0.0,5.0,513.0,497.0
13,34635,27 Feb 2008,MYSORE,17948,38,NaN,V Gharat,58.0,76.51,1200,...,1.0,0.00,0,0.0,1.0,0.0,0.0,5.0,543.0,531.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
382768,32934,23 Feb 2009,HYDERABAD,ZYCON,3,T Srinagesh,J H Christopher,57.5,88.65,1400,...,13.0,25.00,0,0.0,1.0,0.0,0.0,5.0,584.0,608.0
382769,38418,23 Jan 2011,HYDERABAD,ZYCON,5,T Srinagesh,Daniel M Grant,55.5,67.41,1100,...,13.0,25.00,0,0.0,1.0,1.0,0.0,5.0,637.0,627.0
382770,30564,23 Jul 2009,HYDERABAD,ZYCON,3,T Srinagesh,M F Ali Khan,51.0,74.24,1200,...,13.0,25.00,1,1.0,2.0,1.0,1.0,5.0,633.0,650.0
382771,35810,24 Aug 2009,HYDERABAD,ZYCON,3,T Srinagesh,M F Ali Khan,57.0,63.03,1000,...,13.0,25.00,0,1.0,3.0,1.0,0.0,5.0,592.0,646.0
382772,36394,24 Nov 2009,HYDERABAD,ZYCON,3,T Srinagesh,C Ruzaan,59.0,59.90,1000,...,13.0,25.00,1,2.0,3.0,1.0,0.0,5.0,674.0,589.0

In [89]:
# Track_Data_2.loc[:,'Date'] = pd.to_datetime(Track_Data_2['Date'], format=format_string)
# #

In [90]:
Track_Data_2 = Track_Data_2[Track_Data_2['Position'] >= 0]

In [91]:
Track_Data_2['Position'] = Track_Data_2['Position'].astype(int)

<ipython-input-91-281bb79321a7>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  Track_Data_2['Position'] = Track_Data_2['Position'].astype(int)

In [92]:
X = Track_Data_2[features]
y = Track_Data_2[target]
group = Track_Data_2['RaceID']

In [301]:
# Assuming df is your DataFrame
Track_Data_2.loc[:,'Predicted_Speed_Rating'] = Track_Data_2['Predicted_Speed_Rating'] / 10 # Increase influence of speed_rating

In [302]:
Track_Data_2

,RaceID,Date,Venue,Horse,Age,Trainer,Jockey,Wt,Time,Dist,...,Top_3,Win_PCT,Won,Recent_Wins,Recent_Top_3,Recent_Incidents,Incident_Last_Race,Jockey_Rank,Speed_Rating,Predicted_Speed_Rating
4,30710.0,15 Mar 2008,KOLKATA,17639,38.0,NaN,C Alford,54.0,101.53,1600.0,...,4.0,66.67,1.0,2.0,2.0,0.0,0.0,5.0,551.0,550.0
5,37094.0,16 Feb 2008,KOLKATA,17639,38.0,NaN,Neeraj Rawal,48.0,0.00,1600.0,...,4.0,66.67,1.0,3.0,3.0,0.0,0.0,4.0,NaN,556.0
7,36427.0,29 Jul 2007,BANGALORE,17639,37.0,NaN,S John,56.0,71.10,1100.0,...,4.0,66.67,0.0,3.0,3.0,0.0,0.0,4.0,558.0,616.0
8,37780.0,30 Jul 2008,KOLKATA,17639,38.0,NaN,C Alford,57.5,91.03,1400.0,...,4.0,66.67,1.0,3.0,3.0,0.0,0.0,5.0,513.0,497.0
13,34635.0,27 Feb 2008,MYSORE,17948,38.0,NaN,V Gharat,58.0,76.51,1200.0,...,1.0,0.00,0.0,0.0,1.0,0.0,0.0,5.0,543.0,531.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
382769,38418.0,23 Jan 2011,HYDERABAD,ZYCON,5.0,T Srinagesh,Daniel M Grant,55.5,67.41,1100.0,...,13.0,25.00,0.0,0.0,1.0,1.0,0.0,5.0,637.0,627.0
382770,30564.0,23 Jul 2009,HYDERABAD,ZYCON,3.0,T Srinagesh,M F Ali Khan,51.0,74.24,1200.0,...,13.0,25.00,1.0,1.0,2.0,1.0,1.0,5.0,633.0,650.0
382771,35810.0,24 Aug 2009,HYDERABAD,ZYCON,3.0,T Srinagesh,M F Ali Khan,57.0,63.03,1000.0,...,13.0,25.00,0.0,1.0,3.0,1.0,0.0,5.0,592.0,646.0
382772,36394.0,24 Nov 2009,HYDERABAD,ZYCON,3.0,T Srinagesh,C Ruzaan,59.0,59.90,1000.0,...,13.0,25.00,1.0,2.0,3.0,1.0,0.0,5.0,674.0,589.0
Predicted_Speed_Rating,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [303]:
group = group.astype(int)

In [304]:
X

,Wt,Dist,Age,Class,Rtg,Top_3,Win_PCT,Recent_Wins,Recent_Top_3,Predicted_Speed_Rating
4,54.0,1600,38,2.0,74.0,4.0,66.67,2.0,2.0,550.0
5,48.0,1600,38,2.0,62.0,4.0,66.67,3.0,3.0,556.0
7,56.0,1100,37,6.0,0.0,4.0,66.67,3.0,3.0,616.0
8,57.5,1400,38,2.0,78.0,4.0,66.67,3.0,3.0,497.0
13,58.0,1200,38,4.0,42.0,1.0,0.00,0.0,1.0,531.0
...,...,...,...,...,...,...,...,...,...,...
382768,57.5,1400,3,0.0,0.0,13.0,25.00,0.0,1.0,608.0
382769,55.5,1100,5,0.0,89.0,13.0,25.00,0.0,1.0,627.0
382770,51.0,1200,3,2.0,0.0,13.0,25.00,1.0,2.0,650.0
382771,57.0,1000,3,0.0,65.0,13.0,25.00,1.0,3.0,646.0
382772,59.0,1000,3,0.0,84.0,13.0,25.00,2.0,3.0,589.0

In [305]:
y

4          1
5          1
7          5
8          1
13        10
          ..
382768     7
382769     6
382770     1
382771     3
382772     1
Name: Position, Length: 127273, dtype: int64

In [306]:
X_train, X_val, y_train, y_val = train_test_split(X, y, test_size=0.3, random_state=42)

In [147]:
# !pip install catboost

In [148]:
# from catboost import CatBoostRegressor
# from catboost import  Pool

In [149]:
# model = CatBoostRegressor(
#     iterations=1000,
#     learning_rate=0.1,
#     depth=6,
#     loss_function='RMSE',
#     verbose=100
# )

In [150]:
train_race_ids = Track_Data_2.loc[X_train.index, 'RaceID']
val_race_ids = Track_Data_2.loc[X_val.index, 'RaceID']

In [151]:
train_group = train_race_ids.value_counts().sort_index().values
val_group = val_race_ids.value_counts().sort_index().values

In [152]:
scaler = StandardScaler()

In [307]:
X_train_scaled = scaler.fit_transform(X_train)

In [308]:
X_val_scaled = scaler.transform(X_val)

In [155]:
import numpy as np
import lightgbm as lgb
import random

In [309]:
train_data = lgb.Dataset(X_train, label=y_train, group=train_group)

In [310]:
val_data = lgb.Dataset(X_val, label=y_val, group=val_group, reference=train_data)

In [311]:
params = {
    'objective': 'lambdarank',
    'metric': 'ndcg',
    'ndcg_at': [1, 3, 5],
    'learning_rate': 0.1,
    'num_leaves': 31,
    'min_data_in_leaf': 20,
    'verbose': 1,
    'label_gain': list(range(1, y_train.max() + 2))
}

In [190]:
# param_grid = {
#     'learning_rate': [0.01, 0.05, 0.1],
#     'num_leaves': [31, 50, 100],
#     'min_data_in_leaf': [20, 50, 100],
#     'feature_fraction': [0.6, 0.8, 1.0],
#     'bagging_fraction': [0.6, 0.8, 1.0],
#     'lambda_l1': [0.0, 0.1, 1.0],
#     'lambda_l2': [0.0, 0.1, 1.0]
# }

In [183]:
from sklearn.model_selection import GridSearchCV

In [188]:
# grid_search = GridSearchCV(
#     estimator=lgb.LGBMRanker(**params),
#     param_grid=param_grid,
#     cv=3,
#     scoring='neg_mean_squared_error',
#     verbose=1,
#     n_jobs=-1
# )

In [189]:
# grid_search.fit(X_train, y_train, group=train_group)

In [312]:
early_stopping = lgb.early_stopping(stopping_rounds=10)

In [313]:
model = lgb.train(params, train_data, valid_sets=[val_data], callbacks=[early_stopping])

[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.003223 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 800
[LightGBM] [Info] Number of data points in the train set: 89091, number of used features: 10
Training until validation scores don't improve for 10 rounds
Early stopping, best iteration is:
[53]	valid_0's ndcg@1: 0.878403	valid_0's ndcg@3: 0.945678	valid_0's ndcg@5: 0.961053

In [161]:
random_horses = Track_Data_2.loc[X_val.index, 'Horse'].drop_duplicates().sample(n=6, random_state=62)

In [162]:
random_horses

378082                YIPPEE
251517        PORT OF BEAUTY
206029    MASTER OF UNIVERSE
369536          WELCOME BABY
217429                MONTAG
169410            IRISH SONG
Name: Horse, dtype: object

In [163]:
dataset = Track_Data_2.copy()

In [328]:
# Specify the date you're interested in
specific_date = '2024-08-15'

# Filter the DataFrame for the specified date
filtered_df = data[data['Date'] == '06 Apr 2024']
filtered_df
# Extract unique 'RaceID' values
unique_race_ids = filtered_df['RaceID'].unique()

# # Display the result
print(f"Unique RaceIDs on {specific_date}: {unique_race_ids}")

Unique RaceIDs on 2024-08-15: [ 1772  1789  1820  1856  1859  1916  1961  3226  3270  3283  3628 25019]

In [211]:
selected_horses = ['GALLOPING GLORY']

In [251]:
# df_horses_filtered = data[data['Horse'].isin(selected_horses)]
# # df_horses_filtered = df_horses_filtered.drop_duplicates(subset='Horse', keep='first')
# df_horses_filtered

In [206]:
random_race_id = random.choice(val_race_ids.unique())
random_race_id

4741

In [360]:
df_race_filtered_2 = Track_Data_1[Track_Data_1['RaceID'] == 1856]

In [361]:
df_race_filtered_2

,RaceID,Date,Venue,Horse,Age,Trainer,Jockey,Wt,Time,Dist,...,Top_3,Win_PCT,Won,Recent_Wins,Recent_Top_3,Recent_Incidents,Incident_Last_Race,Jockey_Rank,Speed_Rating,Predicted_Speed_Rating
7073,1856,06 Apr 2024,MUMBAI,AFFLUENCE,3,Altamaash Ahmed,K Nazil,54.5,0.0,1000,...,0.0,0.0,0,0.0,0.0,1.0,0.0,5.0,NaN,NaN
33242,1856,06 Apr 2024,MUMBAI,ASHWA SUPREMO,3,M Narredu,Vishal N Bunde,54.5,0.0,1000,...,0.0,0.0,0,0.0,0.0,1.0,0.0,5.0,NaN,NaN
42518,1856,06 Apr 2024,MUMBAI,BASHIR,3,Karthik Ganapathy,Bhawani Singh,56.0,0.0,1000,...,1.0,0.0,0,0.0,1.0,0.0,0.0,4.0,NaN,NaN
69313,1856,06 Apr 2024,MUMBAI,CELESTIAL,3,P Shroff,P S Chouhan,56.0,0.0,1000,...,2.0,0.0,0,0.0,1.0,1.0,0.0,2.0,NaN,NaN
72628,1856,06 Apr 2024,MUMBAI,CHELSEA,3,S K Sunderji,N B Kuldeep,54.5,0.0,1000,...,0.0,0.0,0,0.0,0.0,0.0,0.0,5.0,NaN,NaN
93981,1856,06 Apr 2024,MUMBAI,DAZZLING DUCHESS,3,Dallas Todywalla,P Trevor,54.5,0.0,1000,...,1.0,0.0,0,0.0,0.0,0.0,0.0,1.0,NaN,NaN
93982,1856,06 Apr 2024,MUMBAI,DAZZLING DUCHESS,3,Dallas Todywalla,P Trevor,54.5,0.0,1000,...,1.0,0.0,0,0.0,0.0,0.0,0.0,1.0,NaN,NaN
290332,1856,06 Apr 2024,MUMBAI,SCARLET SENSATION,3,Adhiraj S Jodha,Santosh G,54.5,0.0,1000,...,0.0,0.0,0,0.0,0.0,1.0,0.0,5.0,NaN,NaN
327778,1856,06 Apr 2024,MUMBAI,STORM CLOUD,3,Narendra Lagad,Mustakim Alam,56.0,0.0,1000,...,0.0,0.0,0,0.0,0.0,2.0,0.0,3.0,NaN,NaN
353027,1856,06 Apr 2024,MUMBAI,TOUCH OF GOLD,3,Adhiraj S Jodha,A Sandesh,54.5,0.0,1000,...,2.0,0.0,0,0.0,0.0,1.0,0.0,1.0,NaN,NaN
354894,1856,06 Apr 2024,MUMBAI,TRIGGER,3,Faisal A Abbas,Amyn Merchant,54.5,0.0,1000,...,0.0,0.0,0,0.0,0.0,1.0,0.0,5.0,NaN,NaN
357858,1856,06 Apr 2024,MUMBAI,TURN AND BURN,3,M K Jadhav,N S Parmar,56.0,0.0,1000,...,1.0,50.0,1,1.0,1.0,0.0,0.0,4.0,NaN,NaN

In [362]:
column_names = ['Position', 'Horse']

In [363]:
Actual_Position = df_race_filtered_2[column_names]
Actual_Position

        Position              Horse
7073           6          AFFLUENCE
33242         10      ASHWA SUPREMO
42518          2             BASHIR
69313          3          CELESTIAL
72628          8            CHELSEA
93981          9   DAZZLING DUCHESS
93982         11   DAZZLING DUCHESS
290332        12  SCARLET SENSATION
327778         7        STORM CLOUD
353027         4      TOUCH OF GOLD
354894         5            TRIGGER
357858         1      TURN AND BURN

In [364]:
if not df_race_filtered_2.empty:
    # Select relevant features and horse names
    X_val_race_features_2 = df_race_filtered_2[features]
    horses_2 = df_race_filtered_2['Horse']

In [365]:
X_val_race_features_2

,Wt,Dist,Age,Class,Rtg,Top_3,Win_PCT,Recent_Wins,Recent_Top_3,Predicted_Speed_Rating
7073,54.5,1000,3,1.0,0.0,0.0,0.0,0.0,0.0,NaN
33242,54.5,1000,3,1.0,0.0,0.0,0.0,0.0,0.0,NaN
42518,56.0,1000,3,1.0,0.0,1.0,0.0,0.0,1.0,NaN
69313,56.0,1000,3,1.0,0.0,2.0,0.0,0.0,1.0,NaN
72628,54.5,1000,3,1.0,0.0,0.0,0.0,0.0,0.0,NaN
93981,54.5,1000,3,1.0,0.0,1.0,0.0,0.0,0.0,NaN
93982,54.5,1000,3,1.0,0.0,1.0,0.0,0.0,0.0,NaN
290332,54.5,1000,3,1.0,0.0,0.0,0.0,0.0,0.0,NaN
327778,56.0,1000,3,1.0,0.0,0.0,0.0,0.0,0.0,NaN
353027,54.5,1000,3,1.0,0.0,2.0,0.0,0.0,0.0,NaN
354894,54.5,1000,3,1.0,0.0,0.0,0.0,0.0,0.0,NaN
357858,56.0,1000,3,1.0,0.0,1.0,50.0,1.0,1.0,NaN

In [366]:
X_val_race_scaled_2 = (X_val_race_features_2)

In [367]:
preds_race_2 = model.predict(X_val_race_scaled_2)

In [368]:
results_race_2 = pd.DataFrame({
        'Horse': horses_2,  # Include horse names
        'Prediction': preds_race_2
    })

In [369]:
results_race_2['Rank'] = results_race_2['Prediction'].rank(ascending=True)

In [370]:
results_race_2 = pd.merge(results_race_2, Actual_Position, on='Horse', how='inner')

In [371]:
results_race_2 = results_race_2.sort_values(by='Rank')

In [372]:
print(results_race_2[['Horse', 'Rank','Position']])

                Horse  Rank  Position
13      TURN AND BURN   1.0         1
2              BASHIR   2.0         2
3           CELESTIAL   3.0         3
5    DAZZLING DUCHESS   4.5         9
6    DAZZLING DUCHESS   4.5        11
7    DAZZLING DUCHESS   4.5         9
8    DAZZLING DUCHESS   4.5        11
11      TOUCH OF GOLD   6.0         4
0           AFFLUENCE   9.5         6
1       ASHWA SUPREMO   9.5        10
4             CHELSEA   9.5         8
9   SCARLET SENSATION   9.5        12
10        STORM CLOUD   9.5         7
12            TRIGGER   9.5         5